### ISSUE TITLE
support mysql? or able to change config.php to set "mysqli"

### ISSUE THREAD

**Issue by alemazz** [bitnami/bitnami-docker-moodle#105]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by jotamartos** [comment]
Hi @alemazz, 

Thank you for your interest. You can easily use MySQL instead of MariaDB after changing the container to use (and its environment variables). We tried this docker-compose.yml file and the application was deployed without problems 

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mysql:5.7'
    environment:
      - MYSQL_USER=bn_moodle
      - MYSQL_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
```

Let us know if that works for you as well. 

Thanks
