### ISSUE TITLE
How to customize docker-compose for using persistent storage on Web App?

### ISSUE THREAD

**Issue by Tomohiro-JP** [bitnami/bitnami-docker-moodle#107]
If you have any advices, please give me an advices...

I practice for use Azure Web App with bitnami-moodle, and I set up following https://hub.docker.com/r/bitnami/moodle/.

I tried to use persistent storage following this article (https://docs.microsoft.com/en-US/azure/app-service/containers/tutorial-multi-container-app), but couldn't use...It start initialize after I stop the service few days.

First, I customize top-level volues like this.

```XML
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: ${WEBAPP_STORAGE_HOME}
  moodle_data:
    driver: local
    driver_opts:
      device: ${WEBAPP_STORAGE_HOME}
```

This docker-compose move well, but couldn't use persistent storage.
And then, customize mariadb's volumes like this.

```XML
mariadb:
  volumes:
    - '${WEBAPP_STORAGE_HOME}/mariadb_data:/bitnami'
```

This causes application errors, and couldn't use application causes 503 error.

There's application config "WEBSITES_ENABLE_APP_SERVICE_STORAGE" and value is true on webapps resources on Azure Potral.

How to config with docker-compose.xml to use persistent storage?

**Comment by miguelaeh** [comment]
Hi @Tomohiro-JP ,
Does it work if you change 
```
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: ${WEBAPP_STORAGE_HOME}
  moodle_data:
    driver: local
    driver_opts:
      device: ${WEBAPP_STORAGE_HOME}
```
by
```
volumes:
  mariadb_data:
     driver: local
  moodle_data:
     driver: local
```
?
i.e. without use the `driver_opts`
