### ISSUE TITLE
Can't connect to external DB

### ISSUE THREAD

**Issue by fbotti** [bitnami/bitnami-docker-moodle#109]
Hi, 

I have used the docker-container.yml file with an external DB but It keeps trying to connect to the mysql server. I have tried with an IP and with the name of the server and the problem doesn't seem to be about networking. This is my docker-compose.yml file: 

```yaml
version: '2'

services:
  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - MARIADB_HOST=[HOST_IP]
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=[DB_USER]
      - MOODLE_DATABASE_NAME=[DB_NAME]
      - MOODLE_DATABASE_PASSWORD=[DB_PASSWORD]
      - MOODLE_SKIP_INSTALL=yes
    ports:
      - '8666:80'
      - '4433:443'
    volumes:
      - 'moodle_data:/bitnami'
volumes:
  moodle_data:
    driver: local
```

The problem is that the installation script ends up in timeout whenever it tries to connect to the mysql server.

**Comment by juan131** [comment]
Hi @fbotti 

I guess you're following the steps described at https://github.com/bitnami/bitnami-docker-moodle#use-an-existing-database

One question: is your external database already populated with a Moodle data? If that's not the case, you shouldn't set it to `yes`.

Could you please share the logs of the Moodle container? Just run the command below:

```console
$ docker-compose logs moodle
```

Please add the environment variable below to your **docker-compose.yaml** before doing so to increase the verbosity:

```yaml
...
services:
  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - NAMI_DEBUG='--log-level=trace'
...

**Comment by fbotti** [comment]
Hi @juan131, 

In that database I have an old moodle with data. That's why I tried to skip the installation. I paste here the log of docker-compose log moodle: 

`moodle_1  | app-entrypoint.sh 17:08:59.35 
moodle_1  | app-entrypoint.sh 17:08:59.35 Welcome to the Bitnami moodle container
moodle_1  | app-entrypoint.sh 17:08:59.36 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1  | app-entrypoint.sh 17:08:59.36 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1  | app-entrypoint.sh 17:08:59.36 Send us your feedback at containers@bitnami.com
moodle_1  | app-entrypoint.sh 17:08:59.36 
moodle_1  | nami    INFO  Initializing apache
moodle_1  | nami    INFO  apache successfully initialized
moodle_1  | nami    INFO  Initializing php
moodle_1  | php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/tmp"]
moodle_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/tmp
moodle_1  | php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/logs"]
moodle_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/logs
moodle_1  | php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/var","/opt/bitnami/php/var/log","/opt/bitnami/php/var/run"]
moodle_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var
moodle_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/log
moodle_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/run
moodle_1  | nami    INFO  php successfully initialized
moodle_1  | nami    INFO  Initializing mysql-client
moodle_1  | nami    INFO  mysql-client successfully initialized
moodle_1  | nami    INFO  Initializing moodle
moodle_1  | moodle  DEBUG Preparing apache environment...
moodle_1  | apache  TRACE Skipping reload: com.bitnami.apache not running
moodle_1  | moodle  DEBUG Existing installation, restoring...
moodle_1  | moodle  TRACE [restorePersistedData] Restoring /bitnami/moodle to /opt/bitnami/moodle
moodle_1  | mysql-c INFO  Trying to connect to MySQL server
**moodle_1  | Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries**
moodle_1  | nami    TRACE Error: Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
moodle_1  |     at Object.waitForService (/root/.nami/components/com.bitnami.mysql-client/lib/network.js:77:23)
moodle_1  |     at Object.checkConnection (/root/.nami/components/com.bitnami.mysql-client/lib/databases/mysql/index.js:584:22)
moodle_1  |     at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
moodle_1  |     at MysqlHandler.checkConnection (/root/.nami/components/com.bitnami.moodle/lib/handlers/databases/mysql/index.js:109:15)
moodle_1  |     at Component.$app.postInstallation (/root/.nami/components/com.bitnami.moodle/main.js:51:21)
moodle_1  |     at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
moodle_1  |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
moodle_1  |     at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
moodle_1  |     at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
moodle_1  |     at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
`

**Comment by fbotti** [comment]
It seems to avoid the Environment variable and it keeps trying to connect to internal default DB. This is the error:

>  Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries 
>  nami TRACE Error: Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries

**Comment by juan131** [comment]
Hi @fbotti 

I was unable to reproduce it. To reproduce it, I used the `docker-compose.yaml` below:

```yaml
$ cat docker-compose.yml
version: '2'
services:
  external_database:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bn_password
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_ROOT_PASSWORD=root_password
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=external_database
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bn_password
      - MOODLE_DATABASE_NAME=bitnami_moodle
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - external_database
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
```

Then, I did the following steps:

- Start Moodle and populate the database:

```console
$ docker-compose up -d
# Waint until Moodle was initialized...
$ docker-compose logs -f
(...)
moodle_1             | nami    INFO  moodle successfully initialized
moodle_1             | INFO  ==> Starting moodle...
```

- Stop and remove Moodle


```console
$ docker-compose stop moodle
$ docker-compose rm -v moodle
```

- Modify the **docker-compose.yaml** adding the environment variable below to Moodle:

```
      - MOODLE_SKIP_INSTALL=yes
```

- Start again Moodle:

```console
$ docker-compose up -d
$ docker-compose logs -f
(...)
moodle_1             | mysql-c INFO  Trying to connect to MySQL server
moodle_1             | mysql-c INFO  Found MySQL server listening at external_database:3306
moodle_1             | mysql-c INFO  MySQL server listening and working at external_database:3306
moodle_1             | moodle  INFO  Running Moodle install. Please be patient...
moodle_1             | moodle  INFO  You provided an already initialized Moodle database.
moodle_1             | moodle  INFO  The installation wizard will be skipped and parameters for configuring the user account and SMTP credentials will be ignored.
(...)
moodle_1             | nami    INFO  moodle successfully initialized
moodle_1             | INFO  ==> Starting moodle...
moodle_1             | Starting Apache...
```

**Comment by fbotti** [comment]
Hi @juan131 , 

thanks a lot for helping me out! I believe that the problem appears when you want to connect to a MariaDB/MYSQL in another server with another IP. I have the docker running the apache with PHP and Moodle and in another VPS SERVER with another IP address I have the MYSQL running. I think the problem is when it tries to connect to this remote server. 

In your test you have set it up to point to the same docker instance, trying to reproduce this external database. Could you make your test with an external IP Address? For example:

- MARIADB_HOST=102.154.166.15

That's where it would hangs out trying to reconnect 36 times and then timeouts.

**Comment by juan131** [comment]
Hi @fbotti 

I didn't find any issue when using a MariaDB server that was outside the Docker network. Could you please ensure you have connectivity with that server? E.g. as shown below:

```console
$ docker run --rm -it bitnami/mariadb bash
I have no name!@...:/$ mysql -uroot -h MY_SERVER_HOST -P 3306 -p
```

Are you using a MariaDB or a MySQL server? Please note that's important since you'll have to modify the MySQL client included in the Moodle image when using MySQL (instead of MariaDB).

**Comment by tuananhcwrs** [comment]
Hi @juan131 ,

I have the same issue.
Base on the image 3.9.1 I am trying to connect to external mariaDb host that running in AWS RDS

Here is the set of env vars I use as instructed here https://github.com/bitnami/bitnami-docker-moodle#use-an-existing-database

MOODLE_DATABASE_HOST=
MOODLE_DATABASE_USER=
MOODLE_DATABASE_PASSWORD=
MOODLE_DATABASE_NAME=

And here is the logs (the name of the container is moodle-english-learning):

moodle-english-learning | moodle 07:16:30.55 
moodle-english-learning | moodle 07:16:30.55 INFO  ==> ** Starting Moodle setup **
moodle-english-learning | moodle 07:16:30.61 INFO  ==> Configuring PHP options
moodle-english-learning | moodle 07:16:30.63 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle-english-learning | moodle 07:16:30.70 INFO  ==> Ensuring Moodle directories exist
moodle-english-learning | moodle 07:16:30.72 INFO  ==> Trying to connect to the database server
moodle-english-learning | moodle 07:16:31.12 INFO  ==> Running Moodle install script
moodle-english-learning exited with code 1

Could you please help.
Thanks!

**Comment by juan131** [comment]
Hi @tuananhcwrs 

Could you please share the command or Docker Compose file you're using to deploy Moodle?
Could you also add the environment variable `NAMI_DEBUG=--log-level true`? That will increase the verbosity of the logs so we can obtain more information.

**Comment by tuananhcwrs** [comment]
Hello @juan131 

Thanks for you reply.
Here is the docker-compose content that I use. I build only moodle service because I am going to use external database in AWS RD.

```
version: '3'
services:
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=
      - MOODLE_DATABASE_PASSWORD=
      - MOODLE_DATABASE_NAME=  
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'    
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

as I mentioned in earlier comment, the MOODLE_DATABASE_HOST is the AWS RDS url. I get the account/pass correct but it just exists with code 1.

And the `NAMI_DEBUG=--log-level true` gives no extra info, still the same log I get.

Thanks!

**Comment by juan131** [comment]
Hi @fbotti 

Thanks for sharing it!

Does the database you're indicating at `MOODLE_DATABASE_NAME` exists in your AWS RD? Does the user indicated at `MOODLE_DATABASE_USER` has permissions granted on it? Please note that it must exists in advance.

**Comment by tuananhcwrs** [comment]
Hi @juan131 

All the setting are correct.

We are using the same db server for several apps (each app individual data base/scheme of course). Just only this one cannot work with.

For your information, I fork this https://github.com/jda/docker-moodle, change the database type to mariadb and then I can work with the database.

So there must be something that prevent it within bitnami config.
Thanks!

**Comment by juan131** [comment]
Hi @fbotti 

The Bitnami image should be compatible too.

Is your RDS database based on MariaDB or MySQL? 

- https://aws.amazon.com/rds/mysql/
- https://aws.amazon.com/rds/mariadb/

By the way, the instructions I gave you to enable debug logs were wrong, sorry for that. Instead, please add the line below to your environment section in your Docker Compose:

```
      - NAMI_DEBUG=--log-level trace
```

**Comment by tuananhcwrs** [comment]
Hi @juan131 

It is MariaDB, and version is 10.2.21.
And sorry but no new log I get :(

**Comment by robece** [comment]
Hey fellows!! navigating yesterday I arrived to the same error @tuananhcwrs exposed, I did a pretty good connection locally with MariaDB, but it fails when I point to the company database in MariaDB in Azure, I already disabled the enforce SSL feature temporary from the database and still failing, the only error I can get is:

```
Attaching to moodle-server_moodle-server_1
moodle-server_1 | moodle 13:35:49.60
moodle-server_1 | moodle 13:35:49.61 Welcome to the Bitnami moodle container
moodle-server_1 | moodle 13:35:49.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle-server_1 | moodle 13:35:49.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle-server_1 | moodle 13:35:49.61
moodle-server_1 | moodle 13:35:49.61 INFO ==> ** Starting Moodle setup **
moodle-server_1 | moodle 13:35:49.65 INFO ==> Configuring PHP options
moodle-server_1 | moodle 13:35:49.65 INFO ==> Setting PHP memory_limit option
moodle-server_1 | moodle 13:35:49.67 INFO ==> Validating settings in MYSQL_CLIENT_* env vars
moodle-server_1 | moodle 13:35:49.72 INFO ==> Ensuring Moodle directories exist
moodle-server_1 | moodle 13:35:49.75 INFO ==> Trying to connect to the database server
moodle-server_1 | moodle 13:35:50.43 INFO ==> Running Moodle install script
moodle-server_moodle-server_1 exited with code 1
```

I'm adding the docker-compose I use to create my container:

```
version: '2.4'

services:
  moodle-server:
    #image: bitnami/moodle:3-debian-10
    build:
      context: .
      dockerfile: Dockerfile
    hostname: moodle-server
    environment:
      - NAMI_DEBUG='--log-level=trace'

       # Database
      - MARIADB_HOST=
      - MARIADB_PORT_NUMBER=3306

      - MOODLE_DATABASE_NAME=moodledb
      - MOODLE_DATABASE_USER=
      - MOODLE_DATABASE_PASSWORD=

      # User and Site Configuration
      - MOODLE_SITE_NAME=MoodleSite
      - MOODLE_EMAIL=
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Password.123

      # PHP Environment Variables
      - PHP_MEMORY_LIMIT=500M

      # Installation (if true prevent database configuration)
      - MOODLE_SKIP_INSTALL=no
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - C:\Users\user01\Desktop\Moodle\moodle-server\volume:/bitnami
```

Appreciate any suggestion.
Thanks,
RC

**Comment by robece** [comment]
@tuananhcwrs I think I'm facing the same scenario like you (in real-time) lol... I see my local MariaDB database version is 10.5.4 and my Azure MariaDB database version is 10.3, I don't know if that difference is causing any noise in the moodle's initialization.

**Comment by tuananhcwrs** [comment]
Hi @robece ,

I considered the difference of db version would be the cause. But as I mentioned, the AWS RDS that I use works well with bitnami/wordpress docker image, so I think there should be something else. I don't think Bitnami team make it work with wordpress but not with moodle.

Waiting from @juan131

**Comment by robece** [comment]
Thanks @tuananhcwrs for the quick response, I have another question I'm trying to solve how can I add a certificate to enforce SSL security, hope the team could help us with these scenarios. Thanks everyone.

**Comment by tuananhcwrs** [comment]
Hi @juan131 

Will we have any update for this issue?
Appreciate your support.
Thanks!

**Comment by juan131** [comment]
I could finally enable the debug logs using the Docker Compose below:

```yaml
version: '2'
services:
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      BITNAMI_DEBUG: "true"
      MOODLE_DATABASE_HOST: *****.us-east-1.rds.amazonaws.com
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: admin
      MOODLE_DATABASE_NAME: *****
      MOODLE_DATABASE_PASSWORD: *****
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

As you can see in the logs below, while using a testing RDS database I just created, I found this:

```console
moodle_1  | moodle 08:49:30.79 INFO  ==> Running Moodle install script
moodle_1  |                                  .-..-.
moodle_1  |    _____                         | || |
moodle_1  |   /____/-.---_  .---.  .---.  .-.| || | .---.
moodle_1  |   | |  _   _  |/  _  \/  _  \/  _  || |/  __ \
moodle_1  |   * | | | | | || |_| || |_| || |_| || || |___/
moodle_1  |     |_| |_| |_|\_____/\_____/\_____||_|\_____)
moodle_1  |
moodle_1  | Moodle 3.9.1 (Build: 20200713) command line installation program
moodle_1  | == Environment ==
moodle_1  | !! database mariadb (5.5.5-10.2.21-MariaDB-log) !!
moodle_1  | [System] version 10.2.29 is required and you are running 10.2.21 -
```

Please ensure you're running the right version of MariaDB.
