### ISSUE TITLE
 Cannot connect to MySQL server after docker images restart (gitlab ci)

### ISSUE THREAD

**Issue by lempa** [bitnami/bitnami-docker-moodle#125]
**Description**

Hi, we are using gitlab ci to deploy the whole application. 
We are using following setup

docker-compose.yml

```
---
version: '3.8'
services:

  # --- Database Image
  db:
    image: 'bitnami/mariadb:10.2'
    restart: always
    env_file: .env
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    volumes:
      - db_data:/bitnami/mariadb

  # --- Application Image
  moodle:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
    environment:
      - MARIADB_HOST=${DB_HOST}
      - MARIADB_PORT_NUMBER=${DB_PORT}
      - MOODLE_DATABASE_NAME=${DB_DATABASE}
      - MOODLE_DATABASE_USER=${DB_USERNAME}
      - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD}
      - MOODLE_SITENAME=Moodle Site
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - PHP_MEMORY_LIMIT=2048M
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/www/docker/shared/moodle:/bitnami/moodle
    depends_on:
      - db

volumes:
  db_data:
    driver: local
```

Dockerfile

```
FROM bitnami/moodle:3-debian-10

RUN echo 'de_DE.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen

#moosh
COPY ./app/moosh /bitnami/moosh

# Init
COPY ./resources/docker/scripts /docker-entrypoint-init.d

```

Custom script in ./resources/docker/scripts which is initialised only once

```
# Upgrade moodle
echo "Starting moodle upgrade ..."
/opt/bitnami/php/bin/php /bitnami/moodle/admin/cli/upgrade.php --non-interactive
echo "Moodle upgraded."
```

The .env file

```
# --- DATABSE ENV ---
DB_HOST=db
DB_PORT=3306
DB_DATABASE=staging
DB_USERNAME=staging
DB_PASSWORD=password

# --- DOCKER ENV ---
COMPOSE_PROJECT_NAME=main

# --- MOODLE ENV ---
MOODLE_USERNAME=username
MOODLE_PASSWORD=password
MOODLE_EMAIL=my@example.com

SMTP_HOST=
SMTP_PORT=
SMTP_USER=
SMTP_PASSWORD=
SMTP_PROTOCOL=

```

Generated config.php looks like this:

```
<?php  // Moodle configuration file

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = 'db';
$CFG->dbname    = 'staging';
$CFG->dbuser    = 'staging';
$CFG->dbpass    = 'password;
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => 3306,
  'dbsocket' => '',
  'dbcollation' => 'utf8_general_ci',
);

if (empty($_SERVER['HTTP_HOST'])) {
 $_SERVER['HTTP_HOST'] = '127.0.0.1:80';
    }

    if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
 $CFG->wwwroot   = 'https://' . $_SERVER['HTTP_HOST'];
    } else {
 $CFG->wwwroot   = 'http://' . $_SERVER['HTTP_HOST'];
    };
$CFG->dataroot  = '/bitnami/moodle/moodledata';
$CFG->admin     = 'admin';

$CFG->directorypermissions = 02775;

require_once('/opt/bitnami/moodle' . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!

```

In our gitlab ci pipeline the docker image is build and served to the target server. After the docker container started the moodle install is triggered. After couple of minutes moodle is running perfectly.

Now we have following auto generated IP Gateway / IP Adress

For the db service

```
"Gateway": "192.168.96.1",
"IPAddress": "192.168.96.2",
```

and moodle service

```
"Gateway": "192.168.96.1",
"IPAddress": "192.168.96.3",
```

And now comes the failure. After restarting both containers `(docker-compose down && docker-compose up -d) ` it seems like moodle tries to connect the database in the moodle service instead of to the db service. The error ` Access denied for user 'staging'@'192.168.96.3'` shows the IP Adress from the moodle service. 

Here is the whole error output:

```
Welcome to the Bitnami moodle container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues

nami    INFO  Initializing moodle
moodle  INFO  Preparing PHP environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at db:3306
mysql-c ERROR [canConnect] Connection with 'staging' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'staging' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'staging' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'staging' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'staging' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server:
MySQL command failed to run. Error: 
 ERROR 1045 (28000): Access denied for user 'staging'@'192.168.96.3' (using password: YES)
```

And I don't know why moodle tries to connects to the moodle service and not to the db service, even the mysql server is found with the corresponding name. 

I tried different mariadb versions (10.3, 10.4, 10.5) but nothing helps. The error is the same. The odd thing is it works in the local environment but not in the remote (digitalocean). It doesn't happen on other platforms and services. 
The only way to get launched the services again is to reinstall the whole application.

Do you have any suggestions what might cause this issue.

And here are some additional informations.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 25
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-66-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 985.5MiB
 Name: web-staging
 ID: VQO6:4MK5:IVFB:ZYTH:2VQU:TL27:XP3Y:FJBT:NQ63:RUBG:CQ5N:LJH7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```
