### ISSUE TITLE
Cron Not starting run.sh: line 28: am_i_root: command not found

### ISSUE THREAD

**Issue by juliansworkshop** [bitnami/bitnami-docker-moodle#134]
**Description**
/opt/bitnami/scripts/moodle/run.sh: line 28: am_i_root: command not found
"
if am_i_root; then
    info "** Starting cron **"
    if ! cron_start; then
        error "Failed to start cron. Check that it is installed and its configuration is correct."
        exit 1
    fi
else
    warn "Cron will not be started because of running as a non-root user"
fi
"
am_i_root command doesn't run so debian never attempts to start cron
If I run "service cron start" within the container everything works fine so I believe this is the problem"

**Steps to reproduce the issue:**

1. image: bitnami/moodle:3.9.1-debian-10-r18

**Describe the results you received:**

mododle just sits on asap to run any cron tasks

**Describe the results you expected:**

Expected the cron service to start with the container

**Additional information you deem important (e.g. issue happens only occasionally):**

seems to always happen in my environment am using volumes on /bitnami However this is a new build

**Version**

Client:
 Version:           18.06.2
 API version:       1.38
 Go version:        go1.13.3
 Git commit:        6d37f41
 Built:             Thu Oct 31 06:05:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.13.3
  Git commit:       6d37f41
  Built:            Thu Oct 31 06:13:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- Output of `docker info`:

Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5 (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.79-1.ph3-esx
Operating System: VMware Photon OS/Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.724GiB
Name: EXT-CON0
ID: OFYL:Y2AS:U6IX:6U6W:KF7V:FBJZ:QJT7:JZ52:LHRG:7VRF:WPXH:3WT4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

- Output of `docker-compose version` (if applicable):

docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juliansworkshop** [comment]
No problem thank you for getting that fixed was a little hesitant about using an image I didn't make myself, but this has so far been pretty painless, I'm not seeing a new build on dockerhub yet.

**Comment by javsalgar** [comment]
Hi,

We found an issue with the CI/CD. As soon it is fixed it will be out. If you want, you can add this in moodle run.sh in the meantime.

```
. /opt/bitnami/scripts/libos.sh
```

Just above  `. /opt/bitnami/scripts/liblog.sh`.

**Comment by martinezpenya** [comment]
> Hi,
> 
> We found an issue with the CI/CD. As soon it is fixed it will be out. If you want, you can add this in moodle run.sh in the meantime.
> 
> ```
> . /opt/bitnami/scripts/libos.sh
> ```
> 
> Just above `. /opt/bitnami/scripts/liblog.sh`.

I'm facing the same problem, and after editing this file and restarting container error of line 28 dissapeared, but cron still not working, what i'm missing?

**Comment by jloehel** [comment]
@javsalgar Any news about this? Is sourcing `. /opt/bitnami/scripts/libos.sh` the only issue or is there more?

**Comment by javsalgar** [comment]
Hi,

That should be the only issue, but we are still having issues in the release because of some tests in GKE. I will update the ticket as soon as we have more issues.

**Comment by jloehel** [comment]
> Hi,
> 
> That should be the only issue, but we are still having issues in the release because of some tests in GKE. I will update the ticket as soon as we have more issues.

Thanks for the quick feedback.

**Comment by javsalgar** [comment]
It's finally out! 

https://github.com/bitnami/bitnami-docker-moodle/commit/e96a4fee027401af12f6b43591042b2459d6c9fc

**Comment by jloehel** [comment]
I am not sure but this does not fix it for me. I still have issues to start 3.9.1 or 3.9.2. Only 3.9.0 works for me. Should I open a new report?

**Comment by javsalgar** [comment]
Hi,

Are you still getting the same message? As you can see the missing library is correctly loaded this time.

**Comment by jloehel** [comment]
> Hi,
> 
> Are you still getting the same message? As you can see the missing library is correctly loaded this time.

No, I am getting just this:
```
moodle 16:27:42.20 
moodle 16:27:42.28 Welcome to the Bitnami moodle container
moodle 16:27:42.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle 16:27:42.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle 16:27:42.29 
moodle 16:27:42.29 INFO  ==> ** Starting Moodle setup **
chmod: changing permissions of '/proc/self/fd/1': Permission denied
chmod: changing permissions of '/proc/self/fd/2': Permission denied
```

I am using this stack:
```
version: '2'
services:
  mariadb:
    image: mariadb:10.5.5
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=moodle
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=moodle
    volumes:
     - moodle_db_data:/var/lib/mysql:z
     - moodle_db_backup:/var/lib/backup:z

  moodle:
    image: bitnami/moodle:3.9.2
    ports:
      - '8013:80'
    environment:
     - MOODLE_DATABASE_HOST=mariadb
     - MOODLE_DATABASE_PORT_NUMBER=3306
     - MOODLE_DATABASE_USER=moodle
     - MOODLE_DATABASE_PASSWORD=${MYSQL_PASSWORD}
     - MOODLE_DATABASE_NAME=moodle
     - MOODLE_USERNAME=xxx
     - MOODLE_PASSWORD=${MOODLE_PASSWORD}
     - MOODLE_EMAIL=xxx
     - MOODLE_SITE_NAME=xxx
     - MOODLE_SMTP_HOST=smtp.gmail.com
     - MOODLE_SMTP_PORT=587
     - MOODLE_SMTP_USER=xxx
     - MOODLE_SMTP_PASSWORD=${SMTP_PASSWORD}
     - MOODLE_SMTP_PROTOCOL=tls
     - EXTRA_LOCALES="de_DE.UTF-8 UTF-8, es_ES.UTF-8 UTF-8, es_MX.UTF-8 UTF-8"
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
```
