### ISSUE TITLE
Cant load page after updating to 3.9.1

### ISSUE THREAD

**Issue by martinezpenya** [bitnami/bitnami-docker-moodle#135]
I'm using Docker environment with portainer and Stacks with traefik and no problem with bitnami moodle image version 3.9.0, but when I try to update to latest or 3.9.1... it show no error, only warning, but can't load homepage of moodle.

**Steps to reproduce the issue:**

1. Create new stack
2. Configure new stack as this:
```
version: '2'
services:
  #mariadb:10.1
  ##THIS ONE IS ONLY NEEDED IN CASE OF PERMISSION ISSUES
  fix-mariadb-volume-ownership:
    image: 'bitnami/mariadb:latest'
    container_name: "moodle_db391_fix"
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - '/docker/moodle391/mariadbdata:/bitnami'
    networks:
      - "internal_moodle"
  #------------------------------------------------------    
  moodle_db:
    container_name: "moodle_db391"
    image: 'bitnami/mariadb:latest'
    restart: unless-stopped
    environment:
      - MARIADB_USER=##USER##
      - MARIADB_DATABASE=##DB##
      - MARIADB_PASSWORD=##PASS##
      - MARIADB_ROOT_PASSWORD=##ROOTPASS##
    volumes:
      - '/docker/moodle391/mariadbdata:/bitnami'
    networks:
      - "internal_moodle"
      
  moodle:
    container_name: "moodle391"
    image: 'bitnami/moodle:latest'
    restart: unless-stopped
    environment:
      - MARIADB_HOST=##DB##
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=##DBUSER##
      - MOODLE_DATABASE_NAME=##DBNAME##
      - MOODLE_DATABASE_PASSWORD=##DBPASS##
    ports:
      - '9002:80'
    volumes:
      - '/docker/moodle391/moodledata:/bitnami'
    networks:
      traefik_proxy:
        ipv4_address: 172.28.0.5 #fixed for startup
      internal_moodle:
    depends_on:
      - moodle_db    

networks:
  internal_moodle:
    external:
      name: "internal_moodle"
  traefik_proxy:
    external: 
      name: "traefik_proxy"
```

3. Deploy stack and obtain this in moodle logs:
```
moodle 07:04:48.43 ,
moodle 07:04:48.43 Welcome to the Bitnami moodle container,
moodle 07:04:48.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle,
moodle 07:04:48.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues,
moodle 07:04:48.44 ,
moodle 07:04:48.44 INFO  ==> ** Starting Moodle setup **,
moodle 07:04:48.51 INFO  ==> Configuring PHP options,
moodle 07:04:48.53 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars,
moodle 07:04:48.63 INFO  ==> Restoring persisted Moodle installation,
moodle 07:04:50.26 INFO  ==> Trying to connect to the database server,
moodle 07:04:50.31 INFO  ==> Running database upgrade,
moodle 07:04:50.97 INFO  ==> ** Moodle setup finished! **,
,
/opt/bitnami/scripts/moodle/run.sh: line 28: am_i_root: command not found,
moodle 07:04:50.98 WARN  ==> Cron will not be started because of running as a non-root user,
moodle 07:04:51.00 INFO  ==> ** Starting Apache **,
[Thu Aug 27 07:04:51.051214 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name,
[Thu Aug 27 07:04:51.051632 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name,
[Thu Aug 27 07:04:51.076428 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name,
[Thu Aug 27 07:04:51.076811 2020] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name,
[Thu Aug 27 07:04:51.089194 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.21 configured -- resuming normal operations,
[Thu Aug 27 07:04:51.089249 2020] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND',
```

**Describe the results you received:**
After that it results in can't connect to localhost:9002

**Describe the results you expected:**
With same configuration, only changin image from latest to 3.9.0 works perfectly

**Additional information you deem important (e.g. issue happens only occasionally):**
Firs time I only tried to update my existent installation, now i get same error with fresh installation, I also disabled traefik to see if it works.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:50 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 23
  Running: 18
  Paused: 0
  Stopped: 5
 Images: 21
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-10-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.68GiB
 Name: sheldon
 ID: UKMF:PPS4:R4L2:FA6V:ZYXM:I6QT:RX5O:TFBE:GS5P:KOVI:UGWA:3PTM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
not found (I use compose inside portainer)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Host for docker is a physical i5 with 8GB RAM and debian minimal updated.
