### ISSUE TITLE
docker-compose up: "Running Moodle install script" exits with code 1

### ISSUE THREAD

**Issue by whysthatso** [bitnami/bitnami-docker-moodle#138]
**Description**

**Steps to reproduce the issue:**

1. create docker-compose.yml file

```
version: '3'

services:
  api:
    container_name: my_container
    image: docker.io/bitnami/moodle:3.9.1
    environment:
      - MOODLE_DATABASE_HOST=1.2.3.4
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=db_user_name
      - MOODLE_DATABASE_NAME=db_name
      - MOODLE_DATABASE_PASSWORD=pass
      - MOODLE_PASSWORD=pass
    ports:
      - 1.2.3.4:5555:8080

    volumes:
      - './moodle:/bitnami/moodle'
      - './moodledata:/bitnami/moodledata'

```

2. [Second Step]

run `docker-compose up`

**Describe the results you received:**
the moodle install script exits and the container exits accordingly.

```
docker-compose up
Starting my_container... 
Starting my_container... done
Attaching to eka-moodle-theme
my_container| moodle 13:15:00.83 
my_container| moodle 13:15:00.83 Welcome to the Bitnami moodle container
my_container| moodle 13:15:00.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
my_container| moodle 13:15:00.84 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
my_container| moodle 13:15:00.84 
my_container| moodle 13:15:00.84 INFO  ==> ** Starting Moodle setup **
my_container| moodle 13:15:01.02 INFO  ==> Configuring PHP options
my_container| moodle 13:15:01.07 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
my_container| moodle 13:15:01.36 INFO  ==> Ensuring Moodle directories exist
my_container| moodle 13:15:01.42 INFO  ==> Trying to connect to the database server
my_container| moodle 13:15:01.49 INFO  ==> Running Moodle install script
my_container exited with code 1

```

**Describe the results you expected:**

expecting the install script to finish successfully

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-96-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.899GiB
 Name: app01
 ID: ZYYZ:OOYE:3TH6:RJMM:XABV:ZVAH:IDHE:BF4Z:YCTP:6HL7:NTTL:B4XL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
running on ubuntu 18.04 hetzner vcloud

**Comment by whysthatso** [comment]
running against an external mariadb instance:

```
mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by whysthatso** [comment]
okay, it seems to be an issue with my external mariadb setup. i can run the default docker-compose.yml from this repo.
i think i am actually running the same mariadb version, and i am assuming that

```
my_container| moodle 13:15:01.42 INFO  ==> Trying to connect to the database server
```

means that db access is successful. is there any other test/thing i could do to troubleshoot?

**Comment by andresbono** [comment]
Hi @whysthatso, you can add the `BITNAMI_DEBUG=true` env-var to the Moodle container. That will increment the verbosity of the logs showing the output of the Moodle installation command. Maybe it includes some traces of the error that you are facing.

**Comment by whysthatso** [comment]
ohyeah, that certainly helped. mariadb configuration and version insufficiency after all.

this env var should definitely make it into the standard doc of the image.

**Comment by andresbono** [comment]
That's great! @whysthatso. We will add the env-var in the README, it was already in our plans. Thanks!

**Comment by danieldiazastudillo** [comment]
I'm having the same issue. As @whysthatso, first it was a mariadb version problem. Changed the `docker-compose` file  but now i'm getting the same error. The issue-solving or docs about this it's very scarce. The output it's like this, running containers in WSL2.

```
mariadb_1  | mariadb 18:37:19.64
mariadb_1  | mariadb 18:37:19.65 Welcome to the Bitnami mariadb container
moodle_1   | moodle 18:37:21.01
moodle_1   | moodle 18:37:21.01 Welcome to the Bitnami moodle container
mariadb_1  | mariadb 18:37:19.65 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
moodle_1   | moodle 18:37:21.01 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
mariadb_1  | mariadb 18:37:19.65 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
moodle_1   | moodle 18:37:21.01 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
mariadb_1  | mariadb 18:37:19.66
moodle_1   | moodle 18:37:21.02
moodle_1   | moodle 18:37:21.02 INFO  ==> ** Starting Moodle setup **
mariadb_1  | mariadb 18:37:19.66 INFO  ==> ** Starting MariaDB setup **
mariadb_1  | mariadb 18:37:19.68 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 18:37:19.68 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 18:37:19.69 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 18:37:19.71 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_1  | mariadb 18:37:19.71 WARN  ==> Custom configuration files are not persisted any longer
mariadb_1  | mariadb 18:37:19.72 WARN  ==> Old custom configuration migrated, please manually remove the 'conf' directory from the volume use to persist data
mariadb_1  | mariadb 18:37:19.74 INFO  ==> Setting user option
mariadb_1  | mariadb 18:37:19.76 INFO  ==> Using persisted data
mariadb_1  | mariadb 18:37:19.79 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 18:37:19.79 INFO  ==> Starting mariadb in background
moodle_1   | moodle 18:37:21.04 DEBUG ==> Validating settings in APACHE_* environment variables
moodle_1   | moodle 18:37:21.14 INFO  ==> Configuring PHP options
moodle_1   | moodle 18:37:21.15 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1   | moodle 18:37:21.19 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle_1   | moodle 18:37:21.19 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle_1   | moodle 18:37:21.25 INFO  ==> Ensuring Moodle directories exist
moodle_1   | moodle 18:37:21.29 INFO  ==> Trying to connect to the database server
moodle_1   | moodle 18:37:21.30 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:37:26.31 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:37:31.33 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:37:36.34 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:37:41.36 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:37:46.37 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:37:51.39 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:37:56.40 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:38:01.42 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:38:06.43 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:38:11.45 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:38:16.46 DEBUG ==> Executing SQL command:
moodle_1   | SELECT 1
moodle_1   | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
moodle_1   | moodle 18:38:21.47 ERROR ==> Could not connect to the database
```

I'm not new to Docker but i'm new to a local instance for Moodle. Maybe it's because i have to persist data? It's there a connection-bridge problem? The mariadb container it's running while having this issue. Thanks.

**Comment by danieldiazastudillo** [comment]
Hi @andresbono and thanks for your attention. The `docker-compose.yml` i'm currently trying/testing it's like this:

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle      
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:latest'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

```

It's the official YAML from docs, had to change versions for mariadb and moodle itself. The problema it's clearly mariadb connection, but i've tried with different tags with no luck. Even when trying to connect to the mariadb container (that's runnning)  via VS Code to list items and stuff, it throws a connection error:

![image](https://user-images.githubusercontent.com/14895873/92944491-6ba4fd00-f42a-11ea-8766-d08a96a19cb2.png)

I don't have any firewall rule that blocks this, port it's available and every other Docker container that I use works, this is very strange.
