### ISSUE TITLE
find: ‘/bitnami/moodledata/sessions/’: No such file or directory

### ISSUE THREAD

**Issue by nrctkno** [bitnami/bitnami-docker-moodle#139]
I'm trying to run the instance using the default configuration, and the moodle service throws this error: "find: ‘/bitnami/moodledata/sessions/’: No such file or directory". I'm new in the Docker world so I don't know what am I doing wrong. Any ideas?

Using **Docker 19.03.12 build 48a66213fe @ Windows 10.0.18362 comp. 18362 x64**

**Comment by nrctkno** [comment]
I've switched the version from '2' to '3' in the docker-compose.yml and it seems to be working. Anyway I'm not sure the impact of this change.

**Comment by juan131** [comment]
Hi @nrctkno 

Could you please share the exact Docker Compose and command you're using to deploy Moodle? Thanks in advance.

**Comment by martinezpenya** [comment]
Same problem here, i was working well with 3.9.1 and after recreate container and pull new image (3.9.2) same error and can't stop rebooting
I can't change dockercompose to version 3 (because of portainer).
I've tried to go back to 3.9.1 and same error.
Now I can't access my moodle (help, please)

**Comment by nrctkno** [comment]
> 
> 
> Hi @nrctkno
> 
> Could you please share the exact Docker Compose and command you're using to deploy Moodle? Thanks in advance.

Of course!

docker-compose.yml:

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

```


And I'm running it using `docker-compose up -d`
