### ISSUE TITLE
Missing config.php

### ISSUE THREAD

**Issue by Simon-Peham** [bitnami/bitnami-docker-moodle#143]
I downloadet the docker-compose.yml and try to start the container and the /opt/bitnami/moodle/config.php is missing

and there is a Permission Problem by the mariadb folder /bitnami/mariadb/data

```
$ docker-compose up
Removing moodle_moodle_1_6b43bee66a19
Starting moodle_mariadb_1_5d9a42f14ef5 ... done
Recreating 724a2ef29465_moodle_moodle_1_6b43bee66a19 ... done
Attaching to moodle_mariadb_1_5d9a42f14ef5, moodle_moodle_1_6b43bee66a19
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.74
moodle_1_6b43bee66a19 | moodle 09:39:11.31
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.74 Welcome to the Bitnami mariadb container
moodle_1_6b43bee66a19 | moodle 09:39:11.31 Welcome to the Bitnami moodle container
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.74 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
moodle_1_6b43bee66a19 | moodle 09:39:11.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.74 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
moodle_1_6b43bee66a19 | moodle 09:39:11.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1_6b43bee66a19 | moodle 09:39:11.32
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.75
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.75 INFO  ==> ** Starting MariaDB setup **
moodle_1_6b43bee66a19 | moodle 09:39:11.32 INFO  ==> ** Starting Moodle setup **
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.77 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.77 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1_5d9a42f14ef5 | mariadb 09:39:10.78 INFO  ==> Initializing mariadb database
mariadb_1_5d9a42f14ef5 | mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
moodle_mariadb_1_5d9a42f14ef5 exited with code 1
moodle_1_6b43bee66a19 | moodle 09:39:11.41 INFO  ==> Configuring PHP options
moodle_1_6b43bee66a19 | moodle 09:39:11.43 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1_6b43bee66a19 | moodle 09:39:11.46 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle_1_6b43bee66a19 | moodle 09:39:11.47 WARN  ==> Found 'moodledata' directory inside /bitnami/moodle. Support for this configuration is deprecated and will be removed soon. Please create a new volume mountpoint at /bitnami/moodledata, and copy all its files there.
moodle_1_6b43bee66a19 | moodle 09:39:11.52 INFO  ==> Restoring persisted Moodle installation
moodle_1_6b43bee66a19 | moodle 09:39:13.62 INFO  ==> Trying to connect to the database server
moodle_1_6b43bee66a19 | grep: /opt/bitnami/moodle/config.php: No such file or directory
moodle_moodle_1_6b43bee66a19 exited with code 2

```

**Comment by rafariossaa** [comment]
Hi,
  Could you try running `docker-compose down -v` first ? This will remove any volume related to this compose file.

**Comment by Simon-Peham** [comment]
I have done this yesterday and it didnt help
but it works now

**Comment by ismetbuyar** [comment]
Still running in this error, after docker-compose down -v

(using nginx), docker-compose version 1.29.0, build 07737305, Docker version 20.10.5, build 55c4c88




docker-compose.yml:

```
version: '3.7'

volumes:
  mariadb_moodle_data: {}
  moodle_data: {}

networks:
  moodle: {}

services:

  mariadb-moodle:
    image: 'bitnami/mariadb:10.2'
    networks:
      - moodle
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_moodle_data:/bitnami

  moodle:
    image: 'bitnami/moodle:3'
    depends_on:
      - mariadb-moodle
    networks:
      - moodle
    environment:
      - MARIADB_HOST=mariadb-moodle
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - moodle_data:/bitnami
      - ./moodle/xapiWrapper:/bitnami/moodle/mod/hvp/js
      - ./moodle/view.php:/bitnami/moodle/mod/hvp/view.php
...
```

Log:

```

moodle 19:00:34.32

moodle 19:00:34.33 Welcome to the Bitnami moodle container

moodle 19:00:34.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle

moodle 19:00:34.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues

moodle 19:00:34.33

moodle 19:00:34.34 INFO ==> ** Starting Moodle setup **

moodle 19:00:34.36 DEBUG ==> Validating settings in APACHE_* environment variables

moodle 19:00:34.44 INFO ==> Configuring PHP options

moodle 19:00:34.46 INFO ==> Validating settings in MYSQL_CLIENT_* env vars

moodle 19:00:34.49 DEBUG ==> Validating settings in MOODLE_* environment variables...

moodle 19:00:34.50 WARN ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.

moodle 19:00:34.55 INFO ==> Restoring persisted Moodle installation

moodle 19:00:40.97 INFO ==> Trying to connect to the database server

moodle 19:00:40.97 DEBUG ==> Getting $CFG->dbtype from Moodle configuration

grep: /opt/bitnami/moodle/config.php: No such file or directory

```
