### ISSUE TITLE
Container files complaining about config.php already existing

### ISSUE THREAD

**Issue by JoelFeiner** [bitnami/bitnami-docker-moodle#145]
**Description**

Fresh container will not configure correctly. It shows this in the logs:

```
moodle 16:10:27.85 
moodle 16:10:27.85 Welcome to the Bitnami moodle container
moodle 16:10:27.85 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle 16:10:27.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle 16:10:27.86 
moodle 16:10:27.86 INFO  ==> ** Starting Moodle setup **
moodle 16:10:27.88 DEBUG ==> Validating settings in APACHE_* environment variables
moodle 16:10:27.94 INFO  ==> Configuring PHP options
moodle 16:10:27.96 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 16:10:28.01 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle 16:10:28.08 INFO  ==> Ensuring Moodle directories exist
moodle 16:10:28.13 INFO  ==> Trying to connect to the database server
moodle 16:10:28.13 DEBUG ==> Executing SQL command:
SELECT 1
1
moodle 16:10:28.15 INFO  ==> Running Moodle install script
The configuration file config.php already exists. Please use admin/cli/install_database.php to install Moodle for this site.
```

**Steps to reproduce the issue:**

1. Remove any existing docker containers and mounted volume data.
2. Run docker-compose (see compose file below).
3. MariaDB container comes up fine with created DB.
4. Web container does not succeed and shows the error message above. It immediately restarts, so I have no chance to run the suggested script.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.13, build 4484c46d9d
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.4.238-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.858GiB
 Name: lm.intranet-nyj01.warpwire.net
 ID: 4BLB:QRAU:K3ES:YH4X:URJ3:6EOM:SAE5:BRQY:VE6J:JA2P:5RFS:4J2M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on CentOS 7. Using the following compose file:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    user: 'root'
    container_name: 'moodle_mariadb'
    restart: always
    environment:
     - "MARIADB_ROOT_USER=root"
     - "MARIADB_ROOT_PASSWORD=bitnami"
     - "MARIADB_USER=bn_moodle"
     - "MARIADB_PASSWORD=bitnami"
     - "MARIADB_DATABASE=bitnami_moodle"
    volumes:
     - "/opt/docker_containers/mariadb_moodle:/bitnami"
  moodle:
    image: 'bitnami/moodle:latest'
    container_name: 'moodle_web'
    restart: always
    environment:
     - "MOODLE_DATABASE_HOST=moodle_mariadb"
     - "MOODLE_DATABASE_PORT_NUMBER=3306"
     - "MOODLE_DATABASE_USER=bn_moodle"
     - "MOODLE_DATABASE_PASSWORD=bitnami"
     - "MOODLE_DATABASE_NAME=bitnami_moodle"
     - "BITNAMI_DEBUG=true"
    ports:
     - "3001:80"
     - "3021:443"
    volumes:
     - "/opt/docker_containers/moodle_data:/bitnami"
    depends_on:
     - mariadb
```
