### ISSUE TITLE
cron as non-root user

### ISSUE THREAD

**Issue by samueldmq** [bitnami/bitnami-docker-moodle#148]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

Currently, cron is only configured and ran when running as root:

https://github.com/bitnami/bitnami-docker-moodle/blob/28fb0a20efc079dad9f093837c9198bc50973208/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L176-L182

https://github.com/bitnami/bitnami-docker-moodle/blob/e96a4fee027401af12f6b43591042b2459d6c9fc/3/debian-10/rootfs/opt/bitnami/scripts/moodle/run.sh#L28-L37

**Steps to reproduce the issue:**

1. Run the image
2. Try to copy / clone a course. It runs as cron and will never happen

If cron is not possible, moodle is seriously affected. Multiple functions depend on having cron runnning.
Therefore, it might not be useful to run it as non-root.

**Describe the results you received:**

cron jobs do not run as non-root.

**Describe the results you expected:**

cron jobs run as non-root.

**Additional information you deem important (e.g. issue happens only occasionally):**

No additional info.

**Version**

3.9.2

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using bitnami's helm chart for moodle.

**Comment by juan131** [comment]
Hi @samueldmq 

Thanks so much for reporting issue! I created a task to evaluate alternatives to configure the cronjob when running the container as non-root. 

---

Please note that you can still run the image as root. For instance, if you are using the Moodle chart, you can install it using the **values.yaml** below:

```yaml
## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext:
  enabled: true
  fsGroup: 0

## Configure Container Security Context (only main container)
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
##
containerSecurityContext:
  enabled: true
  runAsUser: 0
```
