### ISSUE TITLE
Docker compose is not working

### ISSUE THREAD

**Issue by divyaksh-shukla** [bitnami/bitnami-docker-moodle#149]
**Description**

I'm trying to run moodle using the supplied docker-compose.yml file, with some modifications.

PS: I even tried the default unchanged docker-compose.yml and that did not work either

```yaml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    hostname: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_PASSWORD=moodle
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

```

**Describe the results you received:**

I get the following errorneous output
```
docker-compose up
Creating network "moodle_default" with the default driver
Creating moodle_mariadb_1 ... done
Creating moodle_moodle_1  ... done
Attaching to moodle_mariadb_1, moodle_moodle_1
mariadb_1  | mariadb 05:45:26.13 
mariadb_1  | mariadb 05:45:26.13 Welcome to the Bitnami mariadb container
mariadb_1  | mariadb 05:45:26.13 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
moodle_1   | moodle 05:45:29.22 
moodle_1   | moodle 05:45:29.22 Welcome to the Bitnami moodle container
moodle_1   | moodle 05:45:29.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1   | moodle 05:45:29.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
mariadb_1  | mariadb 05:45:26.13 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | mariadb 05:45:26.14 
moodle_1   | moodle 05:45:29.23 
moodle_1   | moodle 05:45:29.23 INFO  ==> ** Starting Moodle setup **
mariadb_1  | mariadb 05:45:26.14 INFO  ==> ** Starting MariaDB setup **
mariadb_1  | mariadb 05:45:26.15 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 05:45:26.15 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 05:45:26.15 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 05:45:26.16 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_1  | mariadb 05:45:26.16 INFO  ==> Setting user option
mariadb_1  | mariadb 05:45:26.29 INFO  ==> Using persisted data
mariadb_1  | mariadb 05:45:26.31 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 05:45:26.31 INFO  ==> Starting mariadb in background
moodle_1   | moodle 05:45:29.55 INFO  ==> Configuring PHP options
moodle_1   | moodle 05:45:29.56 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1   | moodle 05:45:29.58 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle_1   | moodle 05:45:29.61 INFO  ==> Ensuring Moodle directories exist
moodle_1   | moodle 05:45:29.63 INFO  ==> Trying to connect to the database server
mariadb_1  | mariadb 05:45:53.03 INFO  ==> Stopping mariadb
mariadb_1  | 
mariadb_1  | mariadb 05:45:55.04 INFO  ==> ** MariaDB setup finished! **
mariadb_1  | mariadb 05:45:55.06 INFO  ==> ** Starting MariaDB **
mariadb_1  | 2020-11-03  5:45:55 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.5.6-MariaDB) starting as process 1 ...
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Uses event mutexes
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Number of pools: 1
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Using SSE4.2 crc32 instructions
mariadb_1  | 2020-11-03  5:45:55 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: 128 rollback segments are active.
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: 10.5.6 started; log sequence number 5308042; transaction id 14182
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1  | 2020-11-03  5:45:55 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2020-11-03  5:45:55 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2020-11-03  5:45:55 0 [Warning] 'proxies_priv' entry '@% root@0c0571d6b6bd' ignored in --skip-name-resolve mode.
mariadb_1  | 2020-11-03  5:45:55 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2020-11-03  5:45:55 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2020-11-03  5:45:55 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.5.6-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
mariadb_1  | 2020-11-03  5:45:55 0 [Note] InnoDB: Buffer pool(s) load completed at 201103  5:45:55
moodle_1   | moodle 05:45:59.68 INFO  ==> Running Moodle install script
moodle_moodle_1 exited with code 1

```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
$ docker version
Client:
 Version:           19.03.12-ce
 API version:       1.40
 Go version:        go1.14.5
 Git commit:        48a66213fe
 Built:             Sat Jul 18 01:33:21 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.5
  Git commit:       48a66213fe
  Built:            Sat Jul 18 01:32:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.1.m
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 364
 Server Version: 19.03.12-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c623d1b36f09f8ef6536a057bd658b3aa8632828.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.72-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.65GiB
 Name: divyaksh-divmanjaro
 ID: VTBN:ZVYQ:SFJP:4MJ4:63HH:WERX:TUN3:2WED:QCHP:CNQZ:MB4S:UM2H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: 674652383234
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose version
docker-compose version 1.27.4, build unknown
docker-py version: 4.3.1
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @divyaksh-shukla 

I'm unable to reproduce it using the default Docker Compose:

```console
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-moodle/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```

Could you please retry adding the `BITNAMI_DEBUG` env. var to your Docker Compose? That env. var will increase the verbosity in the logs:

```diff
...
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    ....
    environment:
+     - BITNAMI_DEBUG=true
    ....
```

Then, share the logs again.

**Comment by abhijeetviswa** [comment]
Hi. I had the same issue. This is the log I got:
```
moodle 20:32:37.19 Welcome to the Bitnami moodle container
moodle 20:32:37.19 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle 20:32:37.19 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle 20:32:37.19
moodle 20:32:37.20 INFO  ==> ** Starting Moodle setup **
moodle 20:32:37.21 DEBUG ==> Validating settings in APACHE_* environment variables
moodle 20:32:37.27 INFO  ==> Configuring PHP options
moodle 20:32:37.27 INFO  ==> Setting PHP expose_php option
moodle 20:32:37.30 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 20:32:37.34 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle 20:32:37.34 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle 20:32:37.39 INFO  ==> Ensuring Moodle directories exist
moodle 20:32:37.43 INFO  ==> Trying to connect to the database server
moodle 20:32:37.43 DEBUG ==> Executing SQL command:
SELECT 1
1
moodle 20:32:37.44 INFO  ==> Running Moodle install script
                                 .-..-.
   _____                         | || |
  /____/-.---_  .---.  .---.  .-.| || | .---.
  | |  _   _  |/  _  \/  _  \/  _  || |/  __ \
  * | | | | | || |_| || |_| || |_| || || |___/
    |_| |_| |_|\_____/\_____/\_____||_|\_____)

Moodle 3.10 (Build: 20201109) command line installation program
Error, incorrect value "admin" for "adminpass"
```

This was the docker-compose.yml file:
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: 'bitnami/moodle:latest'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin
      - BITNAMI_DEBUG=true
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

I fixed my issue by replacing my docker-compose.yml file with the one in the repo. Though I'd love to know what was causing the problem. Thanks :)
