### ISSUE TITLE
ERROR enabling Extra_Locales in docker-compose.yml

### ISSUE THREAD

**Issue by EvanEscent33** [bitnami/bitnami-docker-moodle#150]
**Description**
I wanted to add support for more Languages in Moodle so I did what the documentation on https://hub.docker.com/r/bitnami/moodle/ said and added the following Lines in the docker-compose.yml file after I commented out the image: 

```
...
#image: 'docker.io/bitnami/moodle:3-debian-10' 
   build:
   context: .
     dockerfile: Dockerfile
     args:
       - EXTRA_LOCALES="fr_FR.UTF-8 UTF-8, de_DE.UTF-8 UTF-8, it_IT.UTF-8 UTF-8, es_ES.UTF-8 UTF-8"
...
```

**Steps to reproduce the issue:**

1. [First Step]
     Changed the docker-compose.yml file
2. [Second Step]
    docker-compose up

   
**Describe the results you received:**
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.moodle: 'args'
services.moodle.build contains an invalid type, it should be a string, or an object

**Additional information you deem important (e.g. issue happens only occasionally):**
I double checked the format of the docker-compose.yml file, for missing idents and so on, but the error persists.

**Version**

- Output of `docker version`:
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

- Output of `docker info`:
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-12-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.67GiB
 Name: forest
 ID: 2CBM:XX26:3FA3:DSCO:ZQDN:KTYN:7VBA:VIG6:M27S:3E23:OZZR:WLH3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

- Output of `docker-compose version` (if applicable):
docker-compose version 1.27.2, build 18f557f9

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
the docker runs on an debian Buster host

**Comment by marcosbc** [comment]
Hi @EvanEscent33, it seems there is an indentation typo in the line containing "args:". Make sure it is correct. Here is my working docker-compose.yml:

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXTRA_LOCALES="fr_FR.UTF-8 UTF-8, de_DE.UTF-8 UTF-8, it_IT.UTF-8 UTF-8, es_ES.UTF-8 UTF-8"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
```
