### ISSUE TITLE
EXTRA_LOCALES lead to an error on docker image build

### ISSUE THREAD

**Issue by maxkratz** [bitnami/bitnami-docker-moodle#152]
**Description**

I want to include extra locales e.g. German and French.
Therefore, I've followed the section in readme https://github.com/bitnami/bitnami-docker-moodle#build-the-default-image-with-the-extra_locales-build-time-variable .

**Steps to reproduce the issue:**

1. Clone this repository.
2. cd into `bitnami-docker-moodle/3/debian-10`
3. Edit the file `docker-compose.yml` (just replaced the image with build instructions from readme):

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
#    image: 'docker.io/bitnami/moodle:3-debian-10'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXTRA_LOCALES="fr_FR.UTF-8 UTF-8, de_DE.UTF-8 UTF-8, it_IT.UTF-8 UTF-8, es_ES.UTF-8 UTF-8"
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

4. Run `docker-compose build`.

**Describe the results you received:**

The build fails with this error message:
```
...
Step 23/33 : RUN /opt/bitnami/scripts/locales/add-extra-locales.sh
 ---> Running in 023db164d49f
Enabling locale "fr_FR.UTF-8 UTF-8
Locale "fr_FR.UTF-8 UTF-8 is not supported in this system
ERROR: Service 'moodle' failed to build: The command '/bin/sh -c /opt/bitnami/scripts/locales/add-extra-locales.sh' returned a non-zero code: 1
```

**Describe the results you expected:**

I've expected the build process to finish successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

I've also tried it on another virtual machine (Debian 9 based) to proof that my workstation is the problem, but this does not work either.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 17
  Running: 0
  Paused: 0
  Stopped: 17
 Images: 207
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.6.17-050617-generic
 Operating System: Linux Mint 19.2
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.06GiB
 Name: thinkbrett
 ID: KUMC:VT7F:4XYQ:547V:HEWG:UNMM:2MXV:26GV:2GF5:O2UD:EL23:KLUW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Local Linux Mint 19.2 workstation with Kernel 5.6.17-050617-generic.
