### ISSUE TITLE
selinux /dev/stdout /dev/stderr - permission denied

### ISSUE THREAD

**Issue by jloehel** [bitnami/bitnami-docker-moodle#153]
**Description**
The image tag `3.9.0` works fine in CentOS 7 with SELinux but all images afterwards fail.

**Steps to reproduce the issue:**

1. Change tag from `3.9.0` to `3.10.0`

**Describe the results you received:**
```
moodle 06:46:00.39 ,
moodle 06:46:00.40 Welcome to the Bitnami moodle container,
moodle 06:46:00.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle,
moodle 06:46:00.41 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues,
moodle 06:46:00.41 ,
moodle 06:46:00.41 INFO  ==> ** Starting Moodle setup **,
moodle 06:46:00.53 DEBUG ==> Validating settings in APACHE_* environment variables,
chmod: changing permissions of '/proc/self/fd/1': Permission denied,
chmod: changing permissions of '/proc/self/fd/2': Permission denied,
```

**Describe the results you expected:**

The moodle container starts also with a `3.10.0` image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-203.git0be3e21.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Thu Nov 12 15:11:46 2020
 OS/Arch:         linux/amd64
 Experimental:    false
```

- Output of `docker info`:

```
Containers: 20
 Running: 19
 Paused: 0
 Stopped: 1
Images: 40
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-1160.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 3.669 GiB
Name: XXX
ID: INZA:SWUO:G5BM:KEJP:QWX3:FKVC:PIKP:R5PU:SIKU:5BOY:FCDT:3TRR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by miguelaeh** [comment]
Hi @jloehel ,
Can you share how are you deploying the container? For example, the docker-compose in you case?

**Comment by jloehel** [comment]
This is the current compose-setup

```
version: '2'
services:
  mariadb:
    image: mariadb:10.5.8
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=moodle
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=moodle
    volumes:
     - moodle_db_data:/var/lib/mysql:Z
     - moodle_db_backup:/var/lib/backup:Z

  moodle:
    image: bitnami/moodle:3.9.0
    ports:
      - '8013:80'
    environment:
     - BITNAMI_DEBUG=true
     - MOODLE_DATABASE_HOST=mariadb
     - MOODLE_DATABASE_PORT_NUMBER=3306
     - MOODLE_DATABASE_USER=moodle
     - MOODLE_DATABASE_PASSWORD=${MYSQL_PASSWORD}
     - MOODLE_DATABASE_NAME=moodle
     - MOODLE_USERNAME=xxx
     - MOODLE_PASSWORD=${MOODLE_PASSWORD}
     - MOODLE_EMAIL=xxx@gmail.com
     - MOODLE_SITE_NAME=xxx
     - MOODLE_SMTP_HOST=smtp.gmail.com
     - MOODLE_SMTP_PORT=587
     - MOODLE_SMTP_USER=xxx
     - MOODLE_SMTP_PASSWORD=${SMTP_PASSWORD}
     - MOODLE_SMTP_PROTOCOL=tls
     - EXTRA_LOCALES=de_DE.UTF-8 UTF-8, es_ES.UTF-8 UTF-8, es_MX.UTF-8 UTF-8
    volumes:
      - moodle_data:/bitnami/moodle:Z
      - moodledata_data:/bitnami/moodledata:Z
    depends_on:
      - mariadb
```

**Comment by miguelaeh** [comment]
Hi @jloehel ,
It seems this is a bug related to https://bugzilla.redhat.com/show_bug.cgi?id=1786449 instead of the image itself. Probably because of the migration to non-root.
I would suggest you to try with
```
yum -y reinstall container-selinux
```

And if possible, report more info to the issue in the link above.

**Comment by jloehel** [comment]
> Hi @jloehel ,
> It seems this is a bug related to https://bugzilla.redhat.com/show_bug.cgi?id=1786449 instead of the image itself. Probably because of the migration to non-root.
> I would suggest you to try with
> 
> ```
> yum -y reinstall container-selinux
> ```
> 
> And if possible, report more info to the issue in the link above.

Finally I had some time to debug that. A few setup scripts change the permissions for stdout/stderr but the pseudo terminals get not generated automatically:
```
root@9bac5a8e0f01:/# ls -lahZ /proc/self/fd
total 0
dr-x------. 2 root root system_u:system_r:container_t:s0:c105,c983  0 Apr 20 00:52 .
dr-xr-xr-x. 9 root root system_u:system_r:container_t:s0:c105,c983  0 Apr 20 00:52 ..
lrwx------. 1 root root system_u:system_r:container_t:s0:c105,c983 64 Apr 20 00:52 0 -> /dev/pts/6
lrwx------. 1 root root system_u:system_r:container_t:s0:c105,c983 64 Apr 20 00:52 1 -> /dev/pts/6
lrwx------. 1 root root system_u:system_r:container_t:s0:c105,c983 64 Apr 20 00:52 2 -> /dev/pts/6
lr-x------. 1 root root system_u:system_r:container_t:s0:c105,c983 64 Apr 20 00:52 3 -> /proc/241/fd
root@9bac5a8e0f01:/# ls -lahZ /dev
total 8.0K
drwxr-xr-x. 5 root root system_u:object_r:container_file_t:s0:c105,c983  340 Apr 20 00:31 .
drwxr-xr-x. 1 root root system_u:object_r:container_file_t:s0:c105,c983 4.0K Apr 20 00:31 ..
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c105,c983   11 Apr 20 00:31 core -> /proc/kcore
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c105,c983   13 Apr 20 00:31 fd -> /proc/self/fd
crw-rw-rw-. 1 root root system_u:object_r:container_file_t:s0:c105,c983 1, 7 Apr 20 00:31 full
drwxrwxrwt. 2 root root system_u:object_r:container_file_t:s0:c105,c983   40 Apr 20 00:31 mqueue
crw-rw-rw-. 1 root root system_u:object_r:container_file_t:s0:c105,c983 1, 3 Apr 20 00:31 null
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c105,c983    8 Apr 20 00:31 ptmx -> pts/ptmx
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c105,c983    0 Apr 20 00:31 pts
crw-rw-rw-. 1 root root system_u:object_r:container_file_t:s0:c105,c983 1, 8 Apr 20 00:31 random
drwxrwxrwt. 2 root root system_u:object_r:container_file_t:s0:c105,c983   40 Apr 20 00:31 shm
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c105,c983   15 Apr 20 00:31 stderr -> /proc/self/fd/2
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c105,c983   15 Apr 20 00:31 stdin -> /proc/self/fd/0
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c105,c983   15 Apr 20 00:31 stdout -> /proc/self/fd/1
crw-rw-rw-. 1 root root system_u:object_r:container_file_t:s0:c105,c983 5, 0 Apr 20 00:31 tty
crw-rw-rw-. 1 root root system_u:object_r:container_file_t:s0:c105,c983 1, 9 Apr 20 00:31 urandom
crw-rw-rw-. 1 root root system_u:object_r:container_file_t:s0:c105,c983 1, 5 Apr 20 00:31 zero
root@9bac5a8e0f01:/# ls -lahZ /dev/pts
total 0
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c105,c983    0 Apr 20 00:31 .
drwxr-xr-x. 5 root root system_u:object_r:container_file_t:s0:c105,c983  340 Apr 20 00:31 ..
crw-rw-rw-. 1 root root system_u:object_r:container_file_t:s0:c105,c983 5, 2 Apr 20 00:31 ptmx
```
`/dev/pts/6` does not exist

It's necessary to set `tty` to True in the docker-compose file:
```
  moodle:
    image: bitnami/moodle:3.10.3
    tty: True
...
```
