### ISSUE TITLE
/opt/bitnami/moodle/config.php missing on new installation

### ISSUE THREAD

**Issue by NeaChimeraYoungspace** [bitnami/bitnami-docker-moodle#164]
**Description**

I installed Moodle on Unraid a couple weeks ago, which worked fine.
Later I somehow broke the container by incorrectly installing a Theme.
Now as I had time I decided to just reinstall Moodle, as I did not use it before and it seemed easiert to me, then to just debug what I did wrong.

So now I deleted the folders from /mnt/user/appdata/moodle and /mnt/user/appdata/moodledb where I installed moodle and the mariadb database to.

After installing the dockers again and starting them, this is the output I get
(After starting up, the docker stops itself instantly too)

```
[38;5;6mmoodle [38;5;5m19:35:06.55 [0m
[38;5;6mmoodle [38;5;5m19:35:06.55 [0m[1mWelcome to the Bitnami moodle container[0m
[38;5;6mmoodle [38;5;5m19:35:06.56 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-moodle[0m
[38;5;6mmoodle [38;5;5m19:35:06.56 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-moodle/issues[0m
[38;5;6mmoodle [38;5;5m19:35:06.56 [0m
[38;5;6mmoodle [38;5;5m19:35:06.56 [0m[38;5;2mINFO [0m ==> ** Starting Moodle setup **
[38;5;6mmoodle [38;5;5m19:35:06.67 [0m[38;5;2mINFO [0m ==> Configuring PHP options
[38;5;6mmoodle [38;5;5m19:35:06.67 [0m[38;5;2mINFO [0m ==> Setting PHP memory_limit option
[38;5;6mmoodle [38;5;5m19:35:06.69 [0m[38;5;2mINFO [0m ==> Setting PHP expose_php option
[38;5;6mmoodle [38;5;5m19:35:06.74 [0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_CLIENT_* env vars
[38;5;6mmoodle [38;5;5m19:35:06.86 [0m[38;5;2mINFO [0m ==> Restoring persisted Moodle installation
[38;5;6mmoodle [38;5;5m19:35:08.34 [0m[38;5;2mINFO [0m ==> Trying to connect to the database server
grep: /opt/bitnami/moodle/config.php: No such file or directory
```

**Steps to reproduce the issue:**

1. Setup new moodle and mariadb docker containers as on the screenshot below:
2. On startup you should see the error as above

![moodle](https://user-images.githubusercontent.com/64079948/103444711-74d10880-4c6b-11eb-8a1e-53653a84c122.PNG)
![moodledb](https://user-images.githubusercontent.com/64079948/103444712-7995bc80-4c6b-11eb-8408-84277684ab8f.PNG)

**Describe the results you received:**

Moodle does not start correctly, because a config file is missing.

Moodle should start up correctly

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Server:
 Containers: 48
  Running: 36
  Paused: 0
  Stopped: 12
 Images: 43
 Server Version: 19.03.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.7.3
  Library Version: 101
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.107-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 23.56GiB
 Name: Aeternum
 ID: FIWU:ZHAO:S477:G523:NU36:QEI6:42XB:XUN3:JYGE:DLG5:CCCO:DTUY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
------
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Trying to install Moodle through the Community Applications on Unraid

**Comment by marcosbc** [comment]
Hi @NeaChimeraYoungspace, we can see this line in your logs:

```
 ==> Restoring persisted Moodle installation
```

That means that you did not properly remove persisted Moodle data. It could be possible it is happening because the "data" directory is inside the "moodle" directory. 

Note that the Bitnami Moodle container persists the entire Moodle htdocs directory (where data and files are located), meaning that the "data" directory should NOT be located inside "moodle", as it's meant not to be accessible from the Moodle application, it's a really bad security practice.

We recently made significant changes to the chart and Docker image to fix it, so it could be that you were using an old image. Therefore, I'd suggest to move the data directory outside of there (i.e. to "/mnt/user/appdata/moodledata") and try again after cleaning up persisted volumes.

**Comment by MelonSmasher** [comment]
I'm also getting the same error. Below is my config.

```yaml
version: "3.7"

services:

  mariadb:
    # https://hub.docker.com/r/bitnami/mariadb
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    networks:
      - moodle_network
    environment:
      - MARIADB_USER=<removed>
      - MARIADB_DATABASE=moodle
      - MARIADB_PASSWORD=<removed>
      - MARIADB_ROOT_PASSWORD=<removed>
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - '/opt/moodle/volumes/persistence/mariadb:/bitnami/mariadb'
      - '/opt/moodle/volumes/configs/mariadb/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro'

  moodle:
    # https://hub.docker.com/r/bitnami/moodle
    image: 'docker.io/bitnami/moodle:3.10.1'
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      - moodle_network
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=<removed>
      - MOODLE_DATABASE_PASSWORD=<removed>
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_EMAIL=<removed>
      - MOODLE_PASSWORD=<removed>
      - MOODLE_USERNAME=<removed>
      - MOODLE_SITE_NAME=<removed>
      - MOODLE_SMTP_HOST=<removed>
      - MOODLE_SMTP_PORT=465
      - MOODLE_SMTP_USER=<removed>
      - MOODLE_SMTP_PASSWORD=<removed>
      - MOODLE_SMTP_PROTOCOL=tls
      - PHP_POST_MAX_SIZE=200MB
      - PHP_UPLOAD_MAX_FILESIZE=200MB
    volumes:
      - '/opt/moodle/volumes/persistence/moodle:/bitnami/moodle'
      - '/opt/moodle/volumes/persistence/moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb

networks:
  moodle_network:
    external: true
```

The data directory for MariaDB is created but no other files are created. I tried purging docker from the system then reinstalled it and ensured that there was no data in the persistence mount directories. The issue persists.

```bash
[18:12:01 - 0]
[root@moodle-docker-01:~]# ls -la /opt/moodle/volumes/persistence/mariadb/
total 16
drwxr-xr-x 3 1001 root 4096 Feb 24 18:12 .
drwxr-xr-x 5 1001 root 4096 Feb 24 14:14 ..
drwxr-xr-x 6 1001 root 4096 Feb 24 18:12 data
[18:16:37 - 0]
[root@moodle-docker-01:~]# ls -la /opt/moodle/volumes/persistence/moodle/
total 12
drwxr-xr-x 2 1001 root 4096 Feb 24 14:14 .
drwxr-xr-x 5 1001 root 4096 Feb 24 14:14 ..
[18:16:42 - 0]
[root@moodle-docker-01:~]# ls -la /opt/moodle/volumes/persistence/moodledata/
total 12
drwxr-xr-x 2 1001 root 4096 Feb 24 14:14 .
drwxr-xr-x 5 1001 root 4096 Feb 24 14:14 ..
```

Error:

```
moodle 18:14:33.34 
moodle 18:14:33.34 Welcome to the Bitnami moodle container
moodle 18:14:33.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle 18:14:33.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle 18:14:33.34 
moodle 18:14:33.34 INFO  ==> ** Starting Moodle setup **
moodle 18:14:33.39 INFO  ==> Configuring PHP options
moodle 18:14:33.39 INFO  ==> Setting PHP post_max_size option
moodle 18:14:33.40 INFO  ==> Setting PHP upload_max_filesize option
moodle 18:14:33.42 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 18:14:33.50 INFO  ==> Restoring persisted Moodle installation
moodle 18:14:35.05 INFO  ==> Trying to connect to the database server
grep: /opt/bitnami/moodle/config.php: No such file or directory
```

**Comment by marcosbc** [comment]
Hi @MelonSmasher, unfortunately I could not reproduce your issue even using your official `docker-compose.yml`, as Moodle is properly initialized:

```
moodle_1   | moodle 16:18:48.95
moodle_1   | moodle 16:18:48.96 Welcome to the Bitnami moodle container
moodle_1   | moodle 16:18:48.96 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1   | moodle 16:18:48.96 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1   | moodle 16:18:48.96
moodle_1   | moodle 16:18:48.96 INFO  ==> ** Starting Moodle setup **
moodle_1   | moodle 16:18:49.03 INFO  ==> Configuring PHP options
moodle_1   | moodle 16:18:49.04 INFO  ==> Setting PHP post_max_size option
moodle_1   | moodle 16:18:49.05 INFO  ==> Setting PHP upload_max_filesize option
moodle_1   | moodle 16:18:49.08 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1   | moodle 16:18:49.17 INFO  ==> Ensuring Moodle directories exist
moodle_1   | moodle 16:18:49.20 INFO  ==> Trying to connect to the database server
moodle_1   | moodle 16:19:19.36 INFO  ==> Running Moodle install script
moodle_1   | moodle 16:21:14.17 INFO  ==> Persisting Moodle installation
moodle_1   | moodle 16:21:18.80 INFO  ==> ** Moodle setup finished! **
moodle_1   |
moodle_1   | moodle 16:21:18.81 INFO  ==> ** Starting cron **
moodle_1   | moodle 16:21:18.83 INFO  ==> ** Starting Apache **
```

Note that the logs you provided show this line:

```
moodle 18:14:33.50 INFO  ==> Restoring persisted Moodle installation
```

Meaning the logic detected there being a file inside the "/opt/moodle/volumes/persistence/moodle/" directory. I'm not exactly sure why it's failing for you since you showed the results of `ls -la`, but note that it's working fine for us.

**Comment by Klemich** [comment]
Hi, 
I have a similar problem. 
I need to run the bitnami/moodle image on docker on a synology NAS. 
As I could not use the compose from the terminal (many issues I quite did not get, but not the point), I went through Portainer with a stack. Here is my stack : 
```
version: '2'
services:
  mariadb:
    image: mariadb
    volumes:
      - /volume1/docker/moodle:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_ROOT_USER=***
      - MYSQL_DATABASE=moodle
      
  moodle:
    image: bitnami/moodle:latest
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=***
      - MOODLE_DATABASE_NAME=***
      - PUID=1026
      - PGID=100
    volumes:
      - /volume1/docker/moodle:/bitnami/moodle
      - /volume1/docker/moodleData:/bitnami/moodledata
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
```
After the install, I gor this in the logs of moodle_moodle_1 : 
```
moodle 19:14:24.82 Welcome to the Bitnami moodle container
moodle 19:14:24.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle 19:14:24.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle 19:14:24.82 
moodle 19:14:24.82 INFO  ==> ** Starting Moodle setup **
realpath: /bitnami/apache/conf: No such file or directory
moodle 19:14:24.85 INFO  ==> Configuring Apache ServerTokens directive
moodle 19:14:24.88 INFO  ==> Configuring PHP options
moodle 19:14:24.88 INFO  ==> Setting PHP expose_php option
moodle 19:14:24.90 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 19:14:24.92 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle 19:14:25.03 INFO  ==> Restoring persisted Moodle installatio
moodle 19:14:25.04 INFO  ==> Trying to connect to the database server
```

I'm not a pro IT on that matter, just a teacher, but no-one else to configure moodle on my team. Your help is greatly appreciated.
