### ISSUE TITLE
Unable to boot new bitnami into install with external database

### ISSUE THREAD

**Issue by giliomeejg** [bitnami/bitnami-docker-moodle#172]
I'm setting up a new production environment and would like to use the bitnami docker image primarily for serving php, while keeping my mysql server running on the host (or external with something like AWS RDS).

In order to easily share data with other developers without disclosing passwords, I'm injecting .env variables into docker-compose.yml.

**Steps to reproduce the issue:**

1. [First Step]

Setup directories for:
/var/www/moodle/html
/var/www/moodle/data
/var/www/moodle/moodledata

Inside /var/www/moodle/html, clone the Git repo:
```
git clone git://git.moodle.org/moodle.git
```

2. [Second Step]

Add a docker-compose.yml file that looks as follows:

```
version: "3.8"
services:
  moodle:
    container_name: moodle_web
    image: "docker.io/bitnami/moodle:3-debian-10"
    ports:
      - "8080:8080"
      - "443:8443"
    environment:
      - MOODLE_WWWROOT=${MOODLE_WWWROOT}
      - MOODLE_DATABASE_TYPE=${MOODLE_DATABASE_TYPE}
      - MOODLE_DATABASE_HOST=${MOODLE_DATABASE_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER}
      - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD}
      - MOODLE_SKIP_INSTALL=${MOODLE_SKIP_INSTALL}
      - MOODLE_SKIP_BOOTSTRAP=${MOODLE_SKIP_BOOTSTRAP}
      - BITNAMI_DEBUG=${BITNAMI_DEBUG}
      - MOODLE_TEMPDIR=${MOODLE_TEMPDIR}
      - MOODLE_CACHEDIR=${MOODLE_CACHEDIR}
      - MOODLE_LOCALCACHEDIR=${MOODLE_LOCALCACHEDIR}
    volumes:
      - "${LETSENCRYPT_KEY}:/opt/bitnami/apache/conf/bitnami/certs/server.key:cached"
      - "${LETSENCRYPT_CRT}:/opt/bitnami/apache/conf/bitnami/certs/server.crt:cached"
      - "${MOODLE_DIR}:/bitnami/moodle:cached"
      - "${MOODLE_DATADIR}:/bitnami/moodledata:delegated"
      - "${MOODLE_SESSIONDIR}:/bitnami/moodledata/sessions:delegated"
      - "${MOODLE_TEMPDIR}:/bitnami/moodledata/temp:delegated"
      - "${MOODLE_CACHEDIR}:/bitnami/moodledata/cache:delegated"
      - "${MOODLE_LOCALCACHEDIR}:/bitnami/moodledata/localcache:delegated"
```

3. [Third step]

Add all of your referenced environment variables, as per Step two above, at /var/www/moodle/.env.

A snippet of this variable might look like this:
```
...
MOODLE_DATABASE_TYPE=mysqli
MOODLE_DATABASE_HOST=10.0.1.47
MOODLE_DATABASE_PORT_NUMBER=3306
MOODLE_DATABASE_NAME=moodle_prod
MOODLE_DATABASE_USER=moodle_user
MOODLE_DATABASE_PASSWORD=moodle_password
...
```

4. [Fourth step]

Boot up the container, by going to /var/www/moodle/html and executing:
```
docker-compose --env-file ../.env up
```

**Describe the results you received:**

I'm expecting the container go into "installation mode" as there's no data in moodle/data or moodle/moodledata, and the database does not contain any tables.

**Describe the results you expected:**

Instead, the debug info shows:

```
moodle_web | moodle 23:58:50.68 Welcome to the Bitnami moodle container
moodle_web | moodle 23:58:50.68 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_web | moodle 23:58:50.68 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_web | moodle 23:58:50.68 
moodle_web | moodle 23:58:50.69 INFO  ==> ** Starting Moodle setup **
moodle_web | moodle 23:58:50.70 DEBUG ==> Validating settings in APACHE_* environment variables
moodle_web | moodle 23:58:50.71 INFO  ==> Configuring the HTTPS port
moodle_web | moodle 23:58:50.71 DEBUG ==> Configuring port 8443 on file /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf
moodle_web | moodle 23:58:50.74 INFO  ==> Configuring PHP options
moodle_web | moodle 23:58:50.76 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_web | moodle 23:58:50.79 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle_web | moodle 23:58:50.83 INFO  ==> Restoring persisted Moodle installation
moodle_web | moodle 23:58:52.53 INFO  ==> Trying to connect to the database server
moodle_web | moodle 23:58:52.53 DEBUG ==> Getting $CFG->dbtype from Moodle configuration
moodle_web | moodle 23:58:52.53 DEBUG ==> ^\s*(//\s*)?\$CFG->dbtype\s*=>?([^;,]+)[;,]
moodle_web | moodle 23:58:52.54 DEBUG ==> Getting $CFG->dbhost from Moodle configuration
moodle_web | moodle 23:58:52.54 DEBUG ==> ^\s*(//\s*)?\$CFG->dbhost\s*=>?([^;,]+)[;,]
moodle_web | moodle 23:58:52.55 DEBUG ==> Getting 'dbport' from Moodle configuration
moodle_web | moodle 23:58:52.55 DEBUG ==> ^\s*(//\s*)?'dbport'\s*=>?([^;,]+)[;,]
moodle_web | moodle 23:58:52.56 DEBUG ==> Getting $CFG->dbname from Moodle configuration
moodle_web | moodle 23:58:52.56 DEBUG ==> ^\s*(//\s*)?\$CFG->dbname\s*=>?([^;,]+)[;,]
moodle_web | moodle 23:58:52.57 DEBUG ==> Getting $CFG->dbuser from Moodle configuration
moodle_web | moodle 23:58:52.57 DEBUG ==> ^\s*(//\s*)?\$CFG->dbuser\s*=>?([^;,]+)[;,]
moodle_web | moodle 23:58:52.58 DEBUG ==> Getting $CFG->dbpass from Moodle configuration
moodle_web | moodle 23:58:52.58 DEBUG ==> ^\s*(//\s*)?\$CFG->dbpass\s*=>?([^;,]+)[;,]
moodle_web | moodle 23:58:52.58 INFO  ==> Running database upgrade
moodle_web | Config table does not contain version, can not continue, sorry.
moodle_web | 
moodle_web exited with code 1

```

I expected the initialization script to run for a new instance of moodle.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1038-aws
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.842GiB
 Name: lib.learn.dotrust.org
 ID: FKZR:3EQC:5CSN:3KUF:QCY6:WBYL:EQBH:6KGB:UB27:UON4:F2BB:C6ND
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

AWS EC2 Instance as the host.
