### ISSUE TITLE
Moodle Container stops after start

### ISSUE THREAD

**Issue by jrk-omf** [bitnami/bitnami-docker-moodle#179]
**Description**

I put a fresh installation of the moodle containers with docker compose. The Moodle container starts, but stopped after a couple of seconds without any errormessage

**Steps to reproduce the issue:**

1. docker-compose up -d
2. Wait 10 seconds
3. Moodle Container disappears

**Describe the results you received:**

Container stops

**Describe the results you expected:**

Container is running

**Additional information you deem important (e.g. issue happens only occasionally):**

Output of docker-compose logs moodle:
```
moodle_1   | moodle 23:19:15.60
moodle_1   | moodle 23:19:15.60 Welcome to the Bitnami moodle container
moodle_1   | moodle 23:19:15.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1   | moodle 23:19:15.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1   | moodle 23:19:15.60
moodle_1   | moodle 23:19:15.60 INFO  ==> ** Starting Moodle setup **
moodle_1   | moodle 23:19:15.65 INFO  ==> Configuring PHP options
moodle_1   | moodle 23:19:15.67 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1   | moodle 23:19:15.72 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle_1   | moodle 23:19:15.77 INFO  ==> Ensuring Moodle directories exist
moodle_1   | moodle 23:19:15.81 INFO  ==> Trying to connect to the database server
moodle_1   | moodle 23:19:15.83 INFO  ==> Running Moodle install script
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 109
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-142-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 10
 Total Memory: 62.91GiB
 Name: laberbox
 ID: V5DJ:WJ74:IQEZ:774I:HDCV:LENH:TRBG:AGOI:QGQ3:QQCV:XZT3:JXTG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Content of Dockerfile:

```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - '/data/mariadb:/bitnami/mariadb'
    restart: always
  moodle:
          #    image: docker.io/bitnami/moodle:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8880:8080'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/data/moodle:/bitnami/moodle'
      - '/data/moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb
    restart: always
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

**Comment by gseldon** [comment]
@jrk-omf Hello. 
Can you output `docker-compose up` (without -d) and show error when the container is down.
Output  `ls -l  /data/moodle /data/moodledata` view file permissions.

**Comment by jrk-omf** [comment]
Sure:
```
Creating network "moodle_default" with the default driver
Creating moodle_mariadb_1 ... done
Creating moodle_moodle_1  ... done
Attaching to moodle_mariadb_1, moodle_moodle_1
mariadb_1  | mariadb 08:11:16.41
moodle_1   | moodle 08:11:17.26
moodle_1   | moodle 08:11:17.26 Welcome to the Bitnami moodle container
mariadb_1  | mariadb 08:11:16.41 Welcome to the Bitnami mariadb container
mariadb_1  | mariadb 08:11:16.42 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
moodle_1   | moodle 08:11:17.26 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
mariadb_1  | mariadb 08:11:16.42 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
moodle_1   | moodle 08:11:17.26 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
mariadb_1  | mariadb 08:11:16.42
moodle_1   | moodle 08:11:17.26
mariadb_1  | mariadb 08:11:16.42 INFO  ==> ** Starting MariaDB setup **
moodle_1   | moodle 08:11:17.26 INFO  ==> ** Starting Moodle setup **
mariadb_1  | mariadb 08:11:16.44 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 08:11:16.44 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 08:11:16.44 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 08:11:16.46 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_1  | mariadb 08:11:16.46 INFO  ==> Setting user option
mariadb_1  | mariadb 08:11:16.47 INFO  ==> Setting character_set_server option
mariadb_1  | mariadb 08:11:16.47 INFO  ==> Setting collation_server option
mariadb_1  | mariadb 08:11:16.48 INFO  ==> Using persisted data
mariadb_1  | mariadb 08:11:16.51 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 08:11:16.51 INFO  ==> Starting mariadb in background
moodle_1   | moodle 08:11:17.31 INFO  ==> Configuring PHP options
moodle_1   | moodle 08:11:17.32 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1   | moodle 08:11:17.36 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle_1   | moodle 08:11:17.40 INFO  ==> Ensuring Moodle directories exist
moodle_1   | moodle 08:11:17.43 INFO  ==> Trying to connect to the database server
mariadb_1  | mariadb 08:11:19.41 INFO  ==> Stopping mariadb
mariadb_1  | mariadb 08:11:20.41 INFO  ==> ** MariaDB setup finished! **
mariadb_1  |
mariadb_1  | mariadb 08:11:20.43 INFO  ==> ** Starting MariaDB **
mariadb_1  | 2021-05-14  8:11:20 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.5.10-MariaDB) starting as process 1 ...
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Uses event mutexes
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Number of pools: 1
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mariadb_1  | 2021-05-14  8:11:20 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: 128 rollback segments are active.
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: 10.5.10 started; log sequence number 6683906; transaction id 15195
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1  | 2021-05-14  8:11:20 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2021-05-14  8:11:20 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2021-05-14  8:11:20 0 [Warning] 'proxies_priv' entry '@% root@e278c78d802d' ignored in --skip-name-resolve mode.
mariadb_1  | 2021-05-14  8:11:20 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2021-05-14  8:11:20 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2021-05-14  8:11:20 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.5.10-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
mariadb_1  | 2021-05-14  8:11:20 0 [Note] InnoDB: Buffer pool(s) load completed at 210514  8:11:20
moodle_1   | moodle 08:11:22.46 INFO  ==> Running Moodle install script
moodle_moodle_1 exited with code 1
```

```
/data/moodle:
total 8
drwxrwxr-x 2 daemon root 4096 May 14 00:03 .
drwxr-xr-x 5 root   root 4096 May 14 00:09 ..

/data/moodledata:
total 40
drwxrwxr-x 9 daemon root 4096 May 14 00:14 .
drwxr-xr-x 5 root   root 4096 May 14 00:09 ..
drwxrwxr-x 3 daemon root 4096 May 14 00:46 cache
drwxrwxr-x 2 daemon root 4096 May 14 00:14 filedir
-rw-rw-r-- 1 daemon root  128 May 14 00:13 .htaccess
drwxrwxr-x 2 daemon root 4096 May 14 00:13 lang
drwxrwxr-x 2 daemon root 4096 May 14 00:14 localcache
drwxrwxr-x 2 daemon root 4096 May 14 00:13 muc
drwxrwxr-x 4 daemon root 4096 May 14 00:14 temp
drwxrwxr-x 2 daemon root 4096 May 14 00:14 trashdir
```

**Comment by xoniq** [comment]
Same, just stops. New install

**Comment by alemorcuq** [comment]
Hi, @jrk-omf, @xoniq.

I couldn't reproduce your issue. Here's what I did:

1. Clone the `bitnami/bitnami-docker-moodle` repository
2. `cd` into the `3/debian-10` directory in the repository
3. Modify the `docker-compose.yml` file in that folder to make it like this:
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './mariadb:/bitnami/mariadb'
    restart: always
  moodle:
    #image: docker.io/bitnami/moodle:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8880:8080'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle:/bitnami/moodle'
      - './moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb
    restart: always
 ```
 4. Run `docker-compose up -d && docker-compose logs -f`
 
 The image was built and the application was installed without issues:
 
 ```
moodle_1   | moodle 08:48:54.79 INFO  ==> Running Moodle install script
moodle_1   | moodle 08:51:09.71 INFO  ==> Persisting Moodle installation
moodle_1   | moodle 08:54:13.64 INFO  ==> ** Moodle setup finished! **
moodle_1   |
moodle_1   | moodle 08:54:13.65 INFO  ==> ** Starting cron **
moodle_1   | moodle 08:54:13.67 INFO  ==> ** Starting Apache **
moodle_1   | [Fri May 14 08:54:13.753847 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
```

Did you do any changes to the image you are building in the docker compose file?
