### ISSUE TITLE
Moodle container looping

### ISSUE THREAD

**Issue by strike-noir** [bitnami/bitnami-docker-moodle#181]
**Description**

I am having issue running my docker compose file. The log in the moodle container looping endlessly with texts like these:

```

moodle 20:47:21.88 Welcome to the Bitnami moodle container


moodle 20:47:21.88 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle


moodle 20:47:21.88 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues


moodle 20:47:21.88 


moodle 20:47:21.88 INFO  ==> ** Starting Moodle setup **


moodle 20:47:22.05 INFO  ==> Configuring PHP options


moodle 20:47:22.08 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars


moodle 20:47:22.21 INFO  ==> Restoring persisted Moodle installation


moodle 20:47:22.25 INFO  ==> Trying to connect to the database server


moodle 20:47:22.45 INFO  ==> Running database upgrade
```

**Steps to reproduce the issue:**

My docker compose file looked like this.

```
version: '3.3'

services:
  # Web Application Service Definition
  # --------
  #
  # All of the information needed to start up an odoo web
  # application container.
  moodle:
    container_name: devlearn_web_1

    image: bitnami/moodle

    logging:
      options:
        max-size: "10m"
        max-file: "3"

    depends_on:
        - mariadb

    restart: unless-stopped

    # Port Mapping
    # --------
    #
    # Here we are mapping a port on the host machine (on the left)
    # to a port inside of the container (on the right.) The default
    # port on Odoo is 8069, so Odoo is running on that port inside
    # of the container. But we are going to access it locally on
    # our machine from localhost:9000.
    ports:
       #- 8000:8000
       - 25:25

    # Data Volumes
    # --------
    #
    # This defines files that we are mapping from the host machine
    # into the container.
    #
    # Right now, we are using it to map a configuration file into
    # the container and any extra odoo modules.
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - ./moodle:/bitnami/moodle
      - ./moodledata:/bitnami/moodledata

    # Odoo Environment Variables
    # --------
    #
    # The odoo image uses a few different environment
    # variables when running to connect to the postgres
    # database.
    #
    # Make sure that they are the same as the database user
    # defined in the db container environment variables.
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DOCKER_WEB_PORT=8000
      - ALLOW_EMPTY_PASSWORD=no
      - VIRTUAL_HOST=devlearn.abc.co.id
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=devlearn.abc.co.id
      - LETSENCRYPT_EMAIL=info@abc.co.id

    expose:
      - 8000

  # Database Container Service Definition
  # --------
  #
  # All of the information needed to start up a postgresql
  # container.
  mariadb:
    container_name: devlearn_db_1

    image: mariadb

    logging:
      options:
        max-size: "10m"
        max-file: "3"

    restart: unless-stopped

    # Data Volumes
    # --------
    #
    # This defines files that we are mapping from the host machine
    # into the container.
    #
    # Right now, we are using it to map a configuration file into
    # the container and any extra odoo modules.
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      - ./db:/bitnami/mariadb

    # Database Environment Variables
    # --------
    #
    # The postgresql image uses a few different environment
    # variables when running to create the database. Set the
    # username and password of the database user here.
    #
    # Make sure that they are the same as the database user
    # defined in the web container environment variables.
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_ROOT_PASSWORD=abc

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy

```

**Version**

- Output of `docker version`:

```
Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.2-0ubuntu1~18.04.2
 Built:             Tue Mar 30 21:24:16 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.2-0ubuntu1~18.04.2
  Built:            Mon Mar 29 19:27:41 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.2-dev
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 28
  Running: 27
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-144-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.79GiB
 Name: fhij
 ID: UG4J:GTRU:JWYA:PY3U:4OCG:V74R:Z2PY:OSON:Y2C2:U7XX:ERVI:X2SO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```
