### ISSUE TITLE
Can't redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by alphadijkstra** [bitnami/bitnami-docker-moodle#194]
**Description**

Hey. I have set up an Azure virtual machine with Docker. 
Let's encrypt certificates were generated and added to the server via volume mounting.
For some reason the website does not want to redirect all HTTP traffic via HTTPS

Tried multiple configs with different addresses and ports (127.0.0.1, _default_) in the vhost file. Nothing works :(

I also tried this solution but this one keeps giving me an exit code of 1 (without other logs) every few seconds:
https://github.com/bitnami/bitnami-docker-moodle/issues/116#issuecomment-615332859

**Steps to reproduce the issue:**

Run the following docker-compose.yml
```
version: '3'
services:
  mariadb:
    restart: always
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      - DOCKER_CONTENT_TRUST=1
      - BITNAMI_DEBUG=true
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=anotherpw
      - MARIADB_PASSWORD=mydb
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8
      - MARIADB_COLLATE=utf8_general_ci
    volumes:
      - '/home/path/mariadb:/bitnami/mariadb'
  moodle:
    restart: always
    image: docker.io/bitnami/moodle:latest
    
    healthcheck:
      test: [ "ping", "-c", "1", "-w", "mariadb"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DOCKER_CONTENT_TRUST=1
      - BITNAMI_DEBUG=true
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=mydb
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_SKIP_BOOTSTRAP=yes
      - MOODLE_SKIP_INSTALL=yes
      - PHP_MAX_INPUT_VARS=7000
    volumes:
      - '/home/path/moodle:/bitnami/moodle'
      - '/home/path/moodledata:/bitnami/moodledata'
      - '/home/path/certificates:/certs'
      - '/home/path/apache/vhosts/bitnami.conf:/vhosts/bitnami.conf:ro'
    depends_on:
      - mariadb
```

Contents of bitnami.conf file:

```
# Default Virtual Host configuration.

# Let Apache know we're behind a SSL reverse proxy
SetEnvIf X-Forwarded-Proto https HTTPS=on

<VirtualHost _default_:80>
  DocumentRoot "/opt/bitnami/apache/htdocs"
  # BEGIN: Configuration for letsencrypt
  Include "/opt/bitnami/apps/letsencrypt/conf/httpd-prefix.conf"
  # END: Configuration for letsencrypt
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  Protocols h2 h2c http/1.1
  #H2Direct on
  <Directory "/opt/bitnami/apache/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html
</VirtualHost>

Include "/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf"

```

httpd -S output
```

```

**Describe the results you received:**

The webpage goes to HTTP://mydomain.com

**Describe the results you expected:**

The webpage goes to HTTPS://mydomain.com

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:48 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 6
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-10-cloud-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.349GiB
 Name: VMDocker
 ID: 3WBU:FT2J:VIFX:U5H4:SROH:BPXD:3LCL:UMKG:I62O:52YZ:KUKN:6KGG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version v2.2.2

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on a Docker inside an Azure VM.
