### ISSUE TITLE
bitnami-moodle-docker-nginx

### ISSUE THREAD

**Issue by abdel-hakim** [bitnami/bitnami-docker-moodle#200]
### Name and Version

https://github.com/bitnami/bitnami-docker-moodle.git

### What steps will reproduce the bug?

Hello Heros,
thanks for this amazing app :D 
I know the bitnami-moodle hosting in apache as web-server bulti in a docker image, but this is not satisfied in my server because I want to serve this app by NGINX web-server, so Kindly any tutorials to deploy this app with hosting in Nginx service.
thanks a lot,
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:3
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

### What do you see instead?
```yaml
  nginx:
    image: nginx:alpine
    container_name: ${site_name}-nginx-${env}
    restart: unless-stopped
    tty: true
    ports:
     - "${backend_port}:80"
    depends_on:
     - backend
    volumes:
     - ./conf/nginx/app.conf:/etc/nginx/conf.d/default.conf
```
