### ISSUE TITLE
Debugging moodle container using PhPStorm

### ISSUE THREAD

**Issue by Callustian** [bitnami/bitnami-docker-moodle#203]
### Name and Version

docker.io/bitnami/moodle:3

### What is the problem this feature will solve?

Is it possible to debug the moodle container using PhPStorm?

I have tried (section "Debugging with Xdebug with docker containers") of https://docs.moodle.org/dev/Setting_up_PhpStorm and the docker-compose.yaml I have seems not to accept the XDEBUG_CONFIG and PHP_IDE_CONFIG sections.

Could you help me?
Thanks.

### What is the feature you are proposing to solve the problem?

Something that would not require plenty of changes and that is persisted, is appreciated.

### What alternatives have you considered?

Browsing the internet did not help, possibly I should look for some other search terms (suggestions, please)?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by monasys** [comment]
I got Xdebug working by creating a Dockerfile that uses `bitnami/moodle` as a base image, then installed Xdebug within that:

```
FROM bitnami/moodle

RUN install_packages build-essential autoconf \
    && pecl install xdebug
```
I also made some changes to the `moodle` service in the base `docker-compose.yml`. This has been modified to build the Dockerfile, expose port `9003` and share the Moodle code + Xdebug config between the host & container.

```
moodle:
    build: .
    ports:
      - '80:8080'
      - '443:8443'
    expose:
      - 9003
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './volumes/moodle:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - './conf.d/xdebug.ini:/opt/bitnami/php/etc/conf.d/xdebug.ini'
    depends_on:
      - mariadb
```

`./conf.d/xdebug.ini` contents:

```
zend_extension=xdebug
xdebug.mode=develop,debug
xdebug.client_host=host.docker.internal
```
After starting the containers, I ran `sudo chown -R user:user volumes/moodle` to change the owner of the Moodle code back to myself so that I could edit & step through the code. I use PhpStorm bookmarks to activate the debugger: https://www.jetbrains.com/phpstorm/marklets/
