### ISSUE TITLE
Issue migrating to docker 

### ISSUE THREAD

**Issue by killmasta93** [bitnami/bitnami-docker-moodle#210]
### Name and Version

bitnami/moodle:latest

### What steps will reproduce the bug?

```
1) version: '2'
services:
  mariadb:
    image: mariadb
    volumes:
      - /moodle/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle
      
  moodle:
    image: bitnami/moodle:latest
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
      - PUID=998
      - PGID=100
    volumes:
      - /moodle/Moodle:/bitnami/moodle
      - /moodle/MoodleData:/bitnami/moodledata
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
```

### What do you see instead?

Hi
Currently trying to migrate moodle from one server to another, the issue im having is that the server that im trying to migrate is a docker, trying to follow the steps https://docs.moodle.org/400/en/Moodle_migration
i was able to copy the db and the files, but when copying the public html i see that its different in the config.php settings,
when i try to go the website after migrate the database and files i get error establishing database 
then i restarted the container and it gets stuck on 

```
moodle 15:45:46.68 INFO  ==> Configuring Apache ServerTokens directive

moodle 15:45:46.79 INFO  ==> Configuring PHP options

moodle 15:45:46.79 INFO  ==> Setting PHP expose_php option

moodle 15:45:46.88 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars

moodle 15:45:46.91 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars

moodle 15:45:47.28 INFO  ==> Restoring persisted Moodle installation

moodle 15:45:47.32 INFO  ==> Trying to connect to the database server

moodle 15:45:47.47 INFO  ==> Running database upgrade
```
