### ISSUE TITLE
Cannot start container with SMTP parameters

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-moodle#22]
Launching the container with SMTP configuration breaks the image with the following error log:

```
application_1  | nami    INFO  Initializing apache
application_1  | apache  INFO  ==> Patching httpoxy...
application_1  | nami    INFO  apache successfully initialized
application_1  | nami    INFO  Initializing moodle
application_1  | mysqlCo INFO  Trying to connect to MySQL server
application_1  | mysqlCo INFO  Found MySQL server listening at mariadb:3306
application_1  | mysqlCo INFO  MySQL server listening and working at mariadb:3306
application_1  | Error executing 'postInstallation': ERROR 1062 (23000) at line 1: Duplicate entry 'smtphosts' for key 'mdl_conf_nam_uix'
application_1  |
```

I am using the following `docker-compose.yml` file to launch the container with SMTP configuration.

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/moodle:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=user@gmail.com
      - SMTP_PASSWORD=secretemailpassword
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```
