### ISSUE TITLE
Issue migrating to docker

### ISSUE THREAD

**Issue by killmasta93** [bitnami/bitnami-docker-moodle#221]
### Name and Version

bitnami/moodle:latest

### What steps will reproduce the bug?

1. Copy the www files and create .sql file to the docker container
2.  created docker-compose file
```
version: '2'
services:
  mariadbmoodle:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=moodleuser
      - MARIADB_DATABASE=moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_PASSWORD=mypass
      - MARIADB_ROOT_PASSWORD=mypass
    volumes:
      - /glpi/moodle/moodle.sql:/docker-entrypoint-initdb.d/init.sql:rw # prepopulate database
      - /glpi/moodle/db_data:/var/lib/mysql:rw # persist database data inside docker storage
  moodle:
    image: docker.io/bitnami/moodle:4
    ports:
      - '8097:8080'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=mypass
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - /glpi/moodle/moodle_data:/bitnami/moodle:rw
      - /glpi/moodle/moodledata_data:/bitnami/moodledata:rw
    depends_on:
      - mariadbmoodle
volumes:
  mariadbmoodle_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```
3. edited the config.php
```

<?php  // Moodle configuration file

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = 'mariadbmoodle';
$CFG->dbname    = 'moodle';
$CFG->dbuser    = 'moodleuser';
$CFG->dbpass    = 'mypass';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => '3306',
  'dbsocket' => '',
  'dbcollation' => 'utf8mb4_general_ci',
);

$CFG->wwwroot   = 'https://capacitaciones.domain.com';
$CFG->dataroot  = '/var/www/moodledata';
$CFG->admin     = 'admin';

$CFG->directorypermissions = 0777;

require_once(__DIR__ . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!
```

### What do you see instead?

```
mariadbmoodle_1  | 2022-07-13  5:17:46 15 [Warning] 'proxies_priv' entry '@% root@72a0cdb0ea20' ignored in --skip-name-resolve mode.
mariadbmoodle_1  | find: '/docker-entrypoint-startdb.d/': No such file or directory
mariadbmoodle_1  | mariadb 05:17:47.01 INFO  ==> Stopping mariadb
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] InnoDB: FTS optimize thread exiting.
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] InnoDB: Starting shutdown...
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] InnoDB: Dumping buffer pool(s) to /bitnami/mariadb/data/ib_buffer_pool
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] InnoDB: Restricted to 2028 pages due to innodb_buf_pool_dump_pct=25
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] InnoDB: Buffer pool(s) dump completed at 220713  5:17:47
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] InnoDB: Shutdown completed; log sequence number 31323678; transaction id 3516
mariadbmoodle_1  | 2022-07-13  5:17:47 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: Shutdown complete
mariadbmoodle_1  |
mariadbmoodle_1  | mariadb 05:17:48.03 INFO  ==> ** MariaDB setup finished! **
mariadbmoodle_1  |
mariadbmoodle_1  | mariadb 05:17:48.09 INFO  ==> ** Starting MariaDB **
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (server 10.6.8-MariaDB) starting as process 1 ...
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Number of pools: 1
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Using Linux native AIO
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Completed initialization of buffer pool
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: 128 rollback segments are active.
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: 10.6.8 started; log sequence number 31323678; transaction id 3075
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Warning] 'proxies_priv' entry '@% root@72a0cdb0ea20' ignored in --skip-name-resolve mode.
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadbmoodle_1  | Version: '10.6.8-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
mariadbmoodle_1  | 2022-07-13  5:17:48 0 [Note] InnoDB: Buffer pool(s) load completed at 220713  5:17:48
moodle_1         | moodle 05:17:53.03 INFO  ==> Running database upgrade
moodle_moodle_1 exited with code 255

moodle_1         | moodle 05:18:36.50 Subscribe to project updates by watching https://github.com/bitnami/containers
moodle_1         | moodle 05:18:36.51 Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle_1         | moodle 05:18:36.51
moodle_1         | moodle 05:18:36.51 INFO  ==> ** Starting Moodle setup **
moodle_1         | realpath: /bitnami/apache/conf: No such file or directory
moodle_1         | moodle 05:18:36.61 INFO  ==> Configuring Apache ServerTokens directive
moodle_1         | moodle 05:18:36.71 INFO  ==> Configuring PHP options
moodle_1         | moodle 05:18:36.72 INFO  ==> Setting PHP expose_php option
moodle_1         | moodle 05:18:36.80 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1         | moodle 05:18:36.84 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle_1         | moodle 05:18:37.16 INFO  ==> Restoring persisted Moodle installation
moodle_1         | moodle 05:18:37.21 INFO  ==> Trying to connect to the database server
moodle_1         | moodle 05:18:37.36 INFO  ==> Running database upgrade
moodle_moodle_1 exited with code 255
moodle_1         | moodle 05:19:12.34 Welcome to the Bitnami moodle container
moodle_1         | moodle 05:19:12.35 Subscribe to project updates by watching https://github.com/bitnami/containers
moodle_1         | moodle 05:19:12.35 Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle_1         | moodle 05:19:12.36
moodle_1         | moodle 05:19:12.36 INFO  ==> ** Starting Moodle setup **
moodle_1         | realpath: /bitnami/apache/conf: No such file or directory
moodle_1         | moodle 05:19:12.47 INFO  ==> Configuring Apache ServerTokens directive
moodle_1         | moodle 05:19:12.58 INFO  ==> Configuring PHP options
moodle_1         | moodle 05:19:12.59 INFO  ==> Setting PHP expose_php option
moodle_1         | moodle 05:19:12.67 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle_1         | moodle 05:19:12.70 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle_1         | moodle 05:19:13.02 INFO  ==> Restoring persisted Moodle installation
moodle_1         | moodle 05:19:13.05 INFO  ==> Trying to connect to the database server
moodle_1         | moodle 05:19:13.20 INFO  ==> Running database upgrade
moodle_moodle_1 exited with code 255

```

### Additional information

Hi 
Currently trying to migrate moodle VM to a docker container, I did a backup of the .sql and the files then moved the files into another host which has the containers, but everytime i try to start the container i keep getting an error 

Thank you
