### ISSUE TITLE
docker-compose instance works once, fails on second run

### ISSUE THREAD

**Issue by cobrin** [bitnami/bitnami-docker-moodle#79]
**Description**

Am trying to run Moodle from docker-compose on a Company AWS site. On the first run, it correctly configures the database, and I can connect to the server. On the second time I try and run it, I can't connect to the server I get a 500 error

**Steps to reproduce the issue:**

1. configure docker-compose.yaml
2. docker-compose up
3. ^C (only once)
4. docker-compose up

**Describe the results you received:**

The first run succeeds, and I can login to web server as user "admin". But on trying to run it again, I can no longer connect to the web server

**Describe the results you expected:**

I expect the moodle server to be connectable more than once

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.6.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.7GiB
Name: XXXXXXXXXXXX
ID: VYHI:24SS:VA4J:VXFB:YM5H:GIHN:QHCC:YNTQ:FZU5:XR7V:5KEM:TV4L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

- Contents of docker-compose.yml
```
version: '2'

services:

  # as we want to run docker-compose as user "moodle" but it's volume gets
  # created by user "root" so we need to change the ownership so its sets
  # correctly. We have to use the raw uid, as the container doesn't know
  # user moodle
  fix-mariadb-volume-ownership:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ${MARIADB_LOCAL_DATA_FOLDER}:/bitnami
  fix-moodle-volume-ownership:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ${MOODLE_LOCAL_DATA_FOLDER}:/bitnami

  # Database
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_USER_PASSWORD}
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
    volumes:
      - ${MARIADB_LOCAL_DATA_FOLDER}:/bitnami
    #ports:
    #  - '3306:3306'
    #command:
    #  - chown -R - 1001:1001 /bitnami
    depends_on:
      - fix-mariadb-volume-ownership

  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - NAME_DEBUG=1
      # Database
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_USER_PASSWORD}
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_EMAIL=steve.cobrin@syngenta.com
      - MOODLE_SITENAME=SyngentaMoodleTest

      - MYSQL_CLIENT_CREATE_DATABASE_NAME=${MARIADB_DATABASE}
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_CLIENT_CREATE_DATABASE_USER=${MARIADB_ROOT_USER}

      # User and Site Configuration
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${MOODLE_LOCAL_DATA_FOLDER}:/bitnami
    depends_on:
      - fix-moodle-volume-ownership
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
```
Log of initial start-up
```
[12:45|moodle@deawilmlmp001:/moodle]$ docker-compose up
Creating network "moodle_default" with the default driver
Creating moodle_fix-moodle-volume-ownership_1  ... done
Creating moodle_fix-mariadb-volume-ownership_1 ... done
Creating moodle_mariadb_1                      ... done
Creating moodle_moodle_1                       ... done
Attaching to moodle_fix-mariadb-volume-ownership_1, moodle_fix-moodle-volume-ownership_1, moodle_mariadb_1, moodle_moodle_1
fix-mariadb-volume-ownership_1  |
fix-mariadb-volume-ownership_1  | Welcome to the Bitnami mariadb container
fix-mariadb-volume-ownership_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
fix-mariadb-volume-ownership_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
fix-mariadb-volume-ownership_1  |
moodle_fix-mariadb-volume-ownership_1 exited with code 0
fix-moodle-volume-ownership_1   |
fix-moodle-volume-ownership_1   | Welcome to the Bitnami mariadb container
fix-moodle-volume-ownership_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
fix-moodle-volume-ownership_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
fix-moodle-volume-ownership_1   |
moodle_fix-moodle-volume-ownership_1 exited with code 0
mariadb_1                       |
mariadb_1                       | Welcome to the Bitnami mariadb container
mariadb_1                       | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1                       | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1                       |
moodle_1                        |
moodle_1                        | Welcome to the Bitnami moodle container
moodle_1                        | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1                        | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1                        |
mariadb_1                       | nami    INFO  Initializing mariadb
mariadb_1                       | mariadb INFO  ==> Cleaning data dir...
mariadb_1                       | mariadb INFO  ==> Configuring permissions...
mariadb_1                       | mariadb INFO  ==> Validating inputs...
mariadb_1                       | mariadb INFO  ==> Initializing database...
moodle_1                        | nami    INFO  Initializing apache
moodle_1                        | apache  INFO  ==> Patching httpoxy...
moodle_1                        | nami    INFO  apache successfully initialized
moodle_1                        | nami    INFO  Initializing php
moodle_1                        | nami    INFO  php successfully initialized
moodle_1                        | nami    INFO  Initializing mysql-client
mariadb_1                       | mariadb INFO  ==> Creating 'dbadmin' user with unrestricted access...
mariadb_1                       | mariadb INFO  ==> Creating database moodle...
mariadb_1                       | mariadb INFO  ==> Creating user moodle...
mariadb_1                       | mariadb INFO  ==> Granting access to moodle to the database moodle...
mariadb_1                       | mariadb INFO
mariadb_1                       | mariadb INFO  ########################################################################
mariadb_1                       | mariadb INFO   Installation parameters for mariadb:
mariadb_1                       | mariadb INFO     Root User: dbadmin
mariadb_1                       | mariadb INFO     Root Password: **********
mariadb_1                       | mariadb INFO     Database: moodle
mariadb_1                       | mariadb INFO     Username: moodle
mariadb_1                       | mariadb INFO     Password: **********
mariadb_1                       | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1                       | mariadb INFO  ########################################################################
mariadb_1                       | mariadb INFO
mariadb_1                       | nami    INFO  mariadb successfully initialized
mariadb_1                       | INFO  ==> Starting mariadb...
mariadb_1                       | INFO  ==> Starting mysqld_safe.....
mariadb_1                       | 180809 12:48:04 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1                       | 180809 12:48:04 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
moodle_1                        | mysql-c INFO  Trying to connect to MySQL server
moodle_1                        | mysql-c INFO  Found MySQL server listening at mariadb:3306
moodle_1                        | mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle_1                        | mysql-c INFO  ==> Found database moodle. Skipping database creation...
moodle_1                        | nami    INFO  mysql-client successfully initialized
moodle_1                        | nami    INFO  Initializing moodle
moodle_1                        | mysql-c INFO  Trying to connect to MySQL server
moodle_1                        | mysql-c INFO  Found MySQL server listening at mariadb:3306
moodle_1                        | mysql-c INFO  MySQL server listening and working at mariadb:3306
moodle_1                        | moodle  INFO  Configuring Cron Jobs...
moodle_1                        | moodle  INFO
moodle_1                        | moodle  INFO  ########################################################################
moodle_1                        | moodle  INFO   Installation parameters for moodle:
moodle_1                        | moodle  INFO     Username: admin
moodle_1                        | moodle  INFO     Password: **********
moodle_1                        | moodle  INFO     Email: steve.cobrin@syngenta.com
moodle_1                        | moodle  INFO   (Passwords are not shown for security reasons)
moodle_1                        | moodle  INFO  ########################################################################
moodle_1                        | moodle  INFO
moodle_1                        | nami    INFO  moodle successfully initialized
moodle_1                        | INFO  ==> Starting moodle...
moodle_1                        |
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:23 +0000] "GET / HTTP/1.1" 200 7005
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:24 +0000] "GET /theme/styles.php/boost/1533818934_1533818958/all HTTP/1.1" 200 111215
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:24 +0000] "GET /theme/image.php/boost/core/1533818934/moodlelogo HTTP/1.1" 200 2297
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:24 +0000] "GET /lib/javascript.php/1533818934/lib/requirejs/require.min.js HTTP/1.1" 200 6531
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:24 +0000] "GET /lib/javascript.php/1533818934/lib/javascript-static.js HTTP/1.1" 200 6748
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /theme/yui_combo.php?m/1533818934/core/event/event-min.js&m/1533818934/filter_mathjaxloader/loader/loader-min.js HTTP/1.1" 200 825
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /theme/font.php/boost/core/1533818934/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /lib/requirejs.php/1533818934/core/first.js HTTP/1.1" 200 159607
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /lib/javascript.php/1533818934/lib/jquery/jquery-3.2.1.min.js HTTP/1.1" 200 30081
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:26 +0000] "POST /lib/ajax/service.php?sesskey=ygSMtdFNaK&info=core_fetch_notifications HTTP/1.1" 200 243
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:26 +0000] "GET /theme/image.php/boost/theme/1533818934/favicon HTTP/1.1" 200 1150
moodle_1                        | 127.0.0.1 - - [09/Aug/2018:12:51:27 +0000] "OPTIONS * HTTP/1.0" 200 -
moodle_1                        | 127.0.0.1 - - [09/Aug/2018:12:51:32 +0000] "OPTIONS * HTTP/1.0" 200 -
```

Stopping
```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping moodle_moodle_1                       ... done
Stopping moodle_mariadb_1                      ... done
```

Thjen restarting
```
[12:53|moodle@deawilmlmp001:/moodle]$ docker-compose up
Starting moodle_fix-mariadb-volume-ownership_1 ... done
Starting moodle_fix-moodle-volume-ownership_1  ... done
Starting moodle_mariadb_1                      ... done
Starting moodle_moodle_1                       ... done
Attaching to moodle_fix-mariadb-volume-ownership_1, moodle_fix-moodle-volume-ownership_1, moodle_mariadb_1, moodle_moodle_1
fix-mariadb-volume-ownership_1  |
fix-mariadb-volume-ownership_1  | Welcome to the Bitnami mariadb container
fix-mariadb-volume-ownership_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
fix-mariadb-volume-ownership_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
fix-mariadb-volume-ownership_1  |
fix-moodle-volume-ownership_1   |
fix-moodle-volume-ownership_1   | Welcome to the Bitnami mariadb container
fix-moodle-volume-ownership_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
fix-moodle-volume-ownership_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
fix-moodle-volume-ownership_1   |
moodle_fix-mariadb-volume-ownership_1 exited with code 0
mariadb_1                       |
mariadb_1                       | Welcome to the Bitnami mariadb container
mariadb_1                       | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1                       | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1                       |
moodle_fix-moodle-volume-ownership_1 exited with code 0
moodle_1                        |
moodle_1                        | Welcome to the Bitnami moodle container
moodle_1                        | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-moodle
moodle_1                        | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-moodle/issues
moodle_1                        |
mariadb_1                       | INFO  ==> Starting mariadb...
mariadb_1                       | INFO  ==> Starting mysqld_safe.....
mariadb_1                       | 180809 12:53:33 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1                       | 180809 12:53:33 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
moodle_1                        | INFO  ==> Starting moodle...
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:24 +0000] "GET /lib/javascript.php/1533818934/lib/requirejs/require.min.js HTTP/1.1" 200 6531
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:24 +0000] "GET /lib/javascript.php/1533818934/lib/javascript-static.js HTTP/1.1" 200 6748
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /theme/yui_combo.php?m/1533818934/core/event/event-min.js&m/1533818934/filter_mathjaxloader/loader/loader-min.js HTTP/1.1" 200 825
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /theme/font.php/boost/core/1533818934/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /lib/requirejs.php/1533818934/core/first.js HTTP/1.1" 200 159607
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /lib/javascript.php/1533818934/lib/jquery/jquery-3.2.1.min.js HTTP/1.1" 200 30081
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:26 +0000] "POST /lib/ajax/service.php?sesskey=ygSMtdFNaK&info=core_fetch_notifications HTTP/1.1" 200 243
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:51:26 +0000] "GET /theme/image.php/boost/theme/1533818934/favicon HTTP/1.1" 200 1150
moodle_1                        | 127.0.0.1 - - [09/Aug/2018:12:51:27 +0000] "OPTIONS * HTTP/1.0" 200 -
moodle_1                        | 127.0.0.1 - - [09/Aug/2018:12:51:32 +0000] "OPTIONS * HTTP/1.0" 200 -
moodle_1                        | 172.28.131.99 - - [09/Aug/2018:12:53:51 +0000] "GET / HTTP/1.1" 500 -
```

and finally, you see my next connection fail

Investigating further

```
[12:58|moodle@deawilmlmp001:/moodle]$ docker-compose exec moodle tail -f /opt/bitnami/apache/logs/{access,error}_log
==> /opt/bitnami/apache/logs/access_log <==
172.28.131.99 - - [09/Aug/2018:12:51:24 +0000] "GET /lib/javascript.php/1533818934/lib/javascript-static.js HTTP/1.1" 200 6748
172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /theme/yui_combo.php?m/1533818934/core/event/event-min.js&m/1533818934/filter_mathjaxloader/loader/loader-min.js HTTP/1.1" 200 825
172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /theme/font.php/boost/core/1533818934/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160
172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /lib/requirejs.php/1533818934/core/first.js HTTP/1.1" 200 159607
172.28.131.99 - - [09/Aug/2018:12:51:25 +0000] "GET /lib/javascript.php/1533818934/lib/jquery/jquery-3.2.1.min.js HTTP/1.1" 200 30081
172.28.131.99 - - [09/Aug/2018:12:51:26 +0000] "POST /lib/ajax/service.php?sesskey=ygSMtdFNaK&info=core_fetch_notifications HTTP/1.1" 200 243
172.28.131.99 - - [09/Aug/2018:12:51:26 +0000] "GET /theme/image.php/boost/theme/1533818934/favicon HTTP/1.1" 200 1150
127.0.0.1 - - [09/Aug/2018:12:51:27 +0000] "OPTIONS * HTTP/1.0" 200 -
127.0.0.1 - - [09/Aug/2018:12:51:32 +0000] "OPTIONS * HTTP/1.0" 200 -
172.28.131.99 - - [09/Aug/2018:12:53:51 +0000] "GET / HTTP/1.1" 500 -

==> /opt/bitnami/apache/logs/error_log <==
[Thu Aug 09 12:50:17.507626 2018] [core:notice] [pid 118] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Thu Aug 09 12:53:39.653842 2018] [ssl:warn] [pid 64] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Aug 09 12:53:39.654207 2018] [ssl:warn] [pid 64] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Aug 09 12:53:39.686284 2018] [ssl:warn] [pid 66] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Aug 09 12:53:39.686634 2018] [ssl:warn] [pid 66] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Aug 09 12:53:39.695575 2018] [core:warn] [pid 66] AH00098: pid file /opt/bitnami/apache/tmp/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Aug 09 12:53:39.698070 2018] [mpm_prefork:notice] [pid 66] AH00163: Apache/2.4.34 (Unix) OpenSSL/1.1.0f PHP/7.1.20 configured -- resuming normal operations
[Thu Aug 09 12:53:39.698114 2018] [core:notice] [pid 66] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Thu Aug 09 12:53:51.232392 2018] [php7:warn] [pid 67] [client 172.28.131.99:49266] PHP Warning:  require_once(/bitnami/moodle/config.php): failed to open stream: Permission denied in /bitnami/moodle/index.php on line 30
[Thu Aug 09 12:53:51.232463 2018] [php7:error] [pid 67] [client 172.28.131.99:49266] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/opt/bitnami/php/lib/php') in /bitnami/moodle/index.php on line 30
```

**Comment by tompizmor** [comment]
Hi @cobrin,

At the end the error seems to be this one:

```
[Thu Aug 09 12:53:51.232392 2018] [php7:warn] [pid 67] [client 172.28.131.99:49266] PHP Warning:  require_once(/bitnami/moodle/config.php): failed to open stream: Permission denied in /bitnami/moodle/index.php on line 30
```
So it seems a permission issue because of the change of owner in the moodle data volume.

I have tried with this docker-compose file and worked fine for me:

```
version: '2'

services:

  # as we want to run docker-compose as user "moodle" but it's volume gets
  # created by user "root" so we need to change the ownership so its sets
  # correctly. We have to use the raw uid, as the container doesn't know
  # user moodle
  fix-mariadb-volume-ownership:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ${MARIADB_LOCAL_DATA_FOLDER}:/bitnami

  # Database
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_USER_PASSWORD}
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
    volumes:
      - ${MARIADB_LOCAL_DATA_FOLDER}:/bitnami
    #ports:
    #  - '3306:3306'
    #command:
    #  - chown -R - 1001:1001 /bitnami
    depends_on:
      - fix-mariadb-volume-ownership

  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - NAME_DEBUG=1
      # Database
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_USER_PASSWORD}
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_EMAIL=steve.cobrin@syngenta.com
      - MOODLE_SITENAME=SyngentaMoodleTest

      # User and Site Configuration
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${MOODLE_LOCAL_DATA_FOLDER}:/bitnami
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
```

Also, the following env vars are not necessary in the moodle container because the database is already created by the mariadb container.

```
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=${MARIADB_DATABASE}
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_CLIENT_CREATE_DATABASE_USER=${MARIADB_ROOT_USER}
```
